### ISSUE TITLE
Regex issues

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#104]
I open this issue for all regex related bugs. I am testing the feature right now and expand the issue if necessary.

- [x] `dating|sex|lotto|pharmacy` doesnt work as expected.

works:

- `^(www\.)?fkbook\.co\.uk$|^(www\.)?nsru\.net$|^(www\.)?goo\.gl$|^(www\.)?bit\.ly$`
- `target[t]?ed (visitors|traffic)|viagra|cialis`
- `moncler|north face|vuitton|handbag|burberry|outlet|prada|cialis|viagra|maillot|oakley|ralph lauren|ray ban|iphone|プラダ`

**Comment by schlessera** [comment]
Fixed with #105
