### ISSUE TITLE
Better CSS and different design suggestions

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#116]
In the last merge (#115), we reverted some changes, where it looks like it's worth to put some more discussion into it and the way we reverted those changes were for sure not the way, we should handle this.

# 1. Put margin and padding together
```    
margin: 0 0 0 -10px;
padding: 20px 0 0 0;
```

We have some styles like those above which could be merged together to something like

```
margin: 20px 0 0 -30px;
```

The proposed benefit is less code.

# 2. text-rendering
Is there a benefit in `text-rendering: optimizeLegibility;`?

# 3. Icons
There are different ways to address the rendering of the icons.

# 4 h6
There seems to be an obsolte `clear:both`. Is there a reason for this?

# 5 Screenshots
Basically, I think the best way is to display the screenshots for a discussion:

The current page
![current](https://cloud.githubusercontent.com/assets/6458412/22630211/45e781d8-ebfe-11e6-8606-5629cc07f03d.png)

The reverted
![revert](https://cloud.githubusercontent.com/assets/6458412/22630212/45eb3828-ebfe-11e6-93ac-9b4f799cdadd.png)

Current at breakpoint 1
![current-breakpoint1](https://cloud.githubusercontent.com/assets/6458412/22630209/45db0d7c-ebfe-11e6-93c8-f1dd9118a83d.png)

Revert at breakpoint 1
![revert-breakpoint1](https://cloud.githubusercontent.com/assets/6458412/22630210/45dc2748-ebfe-11e6-8795-5ae0abd2df50.png)

Current at breakpoint 2
![current-breakpoint2](https://cloud.githubusercontent.com/assets/6458412/22630207/45d3d87c-ebfe-11e6-9ac4-cae5f95bcd50.png)

Revert at breakpoint 2
![revert-breakpoint2](https://cloud.githubusercontent.com/assets/6458412/22630208/45dad780-ebfe-11e6-85cb-ee40340f8868.png)

Current at breakpoint 3
![current-breakpoint3](https://cloud.githubusercontent.com/assets/6458412/22630206/45cfc250-ebfe-11e6-8c16-4d8c59c768e5.png)

Revert at breakpoint 3
![revert-breakpoint3](https://cloud.githubusercontent.com/assets/6458412/22630205/45cc877a-ebfe-11e6-90a9-2b82817d1977.png)

Personally, since I felt a bit in a hurry, because we want to release 2.7.0 as quickly as possible, I did went through this debate and changes too quickly, which lead to the problem we are now in. I think, we can discuss ideas about the best way to go at best in an issue and find a solution. Since we really should release 2.7.0, I would vote to give this issue the milestone 2.7.1, but I leave this up to be discussed. But maybe this would help to ease a bit the pressure on this topic and find a good solution for everyone.

If I missed some important point of the discussion, feel free to add it as well. A lot of thought has been put into the reverted changes and I think some suggestions are worth to be considered (like moving the `.ab-column--submit-service` a bit down on the desktop view).

The other point I want to mention is #101. I think we want to do some basic changes in upcoming versions. So for me the scope of this discussion right now is to realize a slightly improved design for some minor versions.

**Comment by Zodiac1978** [comment]
> Is there a benefit in text-rendering: optimizeLegibility;?
See these links:
https://developer.mozilla.org/de/docs/Web/CSS/text-rendering
https://css-tricks.com/almanac/properties/t/text-rendering/
Favors precision in rendering over speed. For example it enables ligatures on text smaller than 20px. On pages with many words (1000+) this can be a performance problem. And there are known issues with Android devices. I have no strong opinion if we should remove it or not. I'm fine with both.

**Comment by websupporter** [comment]
I am closing this for now and would suggest #101 for further discussion regarding UI.
