### ISSUE TITLE
Allow comma separated values in blacklist/whitelist

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#121]
Using a comma separated list of ISO codes ...
![bildschirmfoto 2017-02-08 um 15 22 18](https://cloud.githubusercontent.com/assets/870475/22741207/a4d0cbe4-ee12-11e6-846e-c318e4495581.png)
has this result:
![bildschirmfoto 2017-02-08 um 15 22 32](https://cloud.githubusercontent.com/assets/870475/22741208/a4d9e814-ee12-11e6-88b4-9125e26cc980.png)
I don't think this is the expected result. I Would expect a comma separated list (like in the placeholder). Omitting the space should not have this result and we shouldn't remove the comma.

**Comment by websupporter** [comment]
Needs to be fixed. Will do it this evening.

**Comment by schlessera** [comment]
Resolved with #122
