### ISSUE TITLE
Remove some w.org Tags

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/antispam-bee#123]
From the [WordPress.org Plugin Guidelines](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/):

> Public facing pages, including readmes and translation files, may not be used to spam. Spammy behavior includes (but is not limited to) [...], **tags to competitors plugins, use of over 12 tags total**, [...].

At the moment we have the following tags in our readme: _anti-spam, antispam, block spam, comment, comments, comment spam, pingback, prevention, protect, protection, spam, spam filter, trackback_

Thats 13 tags. So we should get rid of at least one of them. Since they are somewhat redundant, we might as well remove more than one.

Version 2.6.9 shipped with these tags: _comment, spam, antispam, comments, trackback, protection, prevention_

**Comment by Zodiac1978** [comment]
See my comment here:
https://github.com/pluginkollektiv/antispam-bee/pull/53#issuecomment-272833140

**Comment by krafit** [comment]
The changes to w.org Sam describes in this post (referenced in #53) seem great. Lets just remove one of them, to comply with current rules.
Any further changes can be made when necessary.

**Comment by Zodiac1978** [comment]
If I look at our competitors, there is no need to change that. Some plugins have 20+ tags. As long as we don't mention competitors and are not fooling around this seems to be okay.

**Comment by krafit** [comment]
Oh, so nobody is enforcing that rule? 
Well then ¯\_(ツ)_/¯
