### ISSUE TITLE
Spam check: Check for disposable email addresses

### ISSUE THREAD

**Issue by schlessera** [pluginkollektiv/antispam-bee#126]
I suggest adding another optional check to verify whether the provided email is a disposable email account. The reasoning is that a normal person would not use such an email address for personal usage. They are usually used either for spamming or for avoiding getting spammed.

The check should not be enabled by default, because people might legitimately want to not provide their actual email address.

We can use the list from here: https://github.com/nojacko/email-data-disposable/blob/master/data/disposable.txt

**Comment by websupporter** [comment]
Do we have matches with these mail providers in our spam database?

**Comment by schlessera** [comment]
Here's the list of unique domains from our spreadsheet: https://gist.githubusercontent.com/schlessera/fd3594634a96578f30c94a122e093614/raw/96fb58e4804c8cd7932f3d1c0cb27644350a58d1/Undetected%2520spam%2520list%2520-%2520domains

**Comment by schlessera** [comment]
These are in both lists:
```
bigstring.com
gawab.com
```

**Comment by Zodiac1978** [comment]
If a webmaster do not want to allow disposable email addresses this list could be added to the blocklist manually, or not?

It would be just a little bit easier to add ...

**Comment by krafit** [comment]
I think, we should close this issue for now. I can see a future, where this is an add-on for ASB, but I don't think, its a broad enough use case for most users, to be included in ASB.

**Comment by Zodiac1978** [comment]
It is possible to make an addon now. You could use the `option_disallowed_key` filter to add the whole file. Event without ASB involved.

And if you just want to use this for the email in the comment (and not the comment body, user agent, url, etc.) you could take the file and fill up a pattern array with it and use our custom pattern filter.
