### ISSUE TITLE
Spam check: Email address domain has MX record.

### ISSUE THREAD

**Issue by schlessera** [pluginkollektiv/antispam-bee#127]
I suggest adding a new check that verifies whether the email domain has a valid MX record. Only domains with valid MX records should be able to receive emails, so the lack of MX records would hint at the fact that the email is not valid, even though it might fit the general email schema.

The check should not be enabled by default, as it will do a remote request to fetch the MX record(s) of a provided domain.

Also, (maybe far-fetched) it could be abused by spammers to detect the antispam measure in place.

**Comment by Zodiac1978** [comment]
Would be interesting to see how many false email addresses are used. My feeling is, that the most spam is coming from @mail.ru, @gmail.com and @yandex.com/ru. Because the spammer found a way to register an account at these mail providers programmatically. Have you some data for us on this?

**Comment by krafit** [comment]
Is there a smart way to collect data about (in)valid MX records? This would be super interesting for some further research.

**Comment by schlessera** [comment]
http://php.net/manual/de/function.checkdnsrr.php

**Comment by schlessera** [comment]
Oder eventuell: http://php.net/manual/de/function.getmxrr.php

**Comment by Zodiac1978** [comment]
getmxrr seems to be not the right choice ...
> This function should not be used for the purposes of address verification.

**Comment by krafit** [comment]
I thought about: packing the MX-checkup together in a small ASB-addon, install it on selected sites and fetch the gathered data in a central place for further (manual) analysis.

@schlessera do you think it's possible to do this without too much overhead? The _fetching and gathering data for analysis_ part could be reused for future checks as well.

**Comment by schlessera** [comment]
To collect the data, we could look at Amazon SimpleDB: https://aws.amazon.com/simpledb/pricing/
I would guess that, at least for our foreseeable future needs, we will still stay within the free tier 1 GB of data per month and 25 hours of DB processing per month.

**Comment by schlessera** [comment]
Writing an addon is currently not that easy, as the code is not really modular.

But very generally, we could write a separate "data collection" plugin that people can install if they intend to help research for the project.

The main question is: where will we store the data?

**Comment by schlessera** [comment]
Erm... wrong order of comments :D

**Comment by Zodiac1978** [comment]
@schlessera Did you check the domains from [your list](https://gist.githubusercontent.com/schlessera/fd3594634a96578f30c94a122e093614/raw/96fb58e4804c8cd7932f3d1c0cb27644350a58d1/Undetected%2520spam%2520list%2520-%2520domains) - do those domains provide a MX record?

**Comment by stklcode** [comment]
Don‘t forget to be careful with what you get as MX RR. Simple presence of at least one entry says nothing about valid mail setup at all. Beside the already mentioned fact that probably a high percentage of spammers just use free mail hosters.

I did an evaluation on around 100mio domains some time ago and there is just about everything to be found in the wild, from company-internal records with prio. 10 + public fallback on 60 (not nice, but it works) to localhost loopbacks and all sorts of non-spec configurations like IPs, CNAMES, etc. and finally couple of thousand systems with arbitrary text messages.
Same for other way, not every mail server is able to transport mails...

**Comment by Zodiac1978** [comment]
After the last comment it looks like a MX record is not a reliable option to check for.
