### ISSUE TITLE
Add a filter for replacing multiple comment froms

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#128]
This is an edge case from the support forums.
https://wordpress.org/support/topic/comment-form-used-outside-of-posts-not-working-properly/

A theme is showing the comment form below every post on the archive page. But the `preg_replace` is limited to 1. Maybe we could add a filter for this?

I don't want to add an option for this, but a filter could help. On the other side this is really an edge case ...

What do you think?

**Comment by websupporter** [comment]
I just checked. Basically its still the same situation in `2.7.0`. Yes, if we want to solve it, I would suggest to go with the filter. Yes, I think its really an edge case. Not really high on my priority list. But if a PR drops by with a filter in it :tada: :smiley:
