### ISSUE TITLE
Chrome autofill seems to mistake the comment field for an address field

### ISSUE THREAD

**Issue by schlessera** [pluginkollektiv/antispam-bee#130]
On some sites, Chrome Autofill mistakenly fills out the `comment` field as if it where a street address field, as reported here: https://wordpress.org/support/topic/merkwurdiges-verhalten/#post-8812548

I suggest adding hints for browser so that they can make out what the different form fields mean, and set the actual comment field to `autofill off`.

Link to spec: https://html.spec.whatwg.org/multipage/forms.html#autofill

**Comment by Drivingralle** [comment]
Doesn't hints make it easier for bots to create "good looking" comments again?

**Comment by schlessera** [comment]
The hint will basically state that the `name` field is a "Name" field, that the `email` field is an "Email" field, that the `website` field is a "Website" field, and that the `5d6a31b3ff` field should not be autofilled.

I don't think that will give any further advantage to bots.

**Comment by swissspidy** [comment]
I still want to know why Chrome is doing this. Of course disabling autofill might sense, but if we can figure out the bigger picture, that would be even better.
