### ISSUE TITLE
Comment empty

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#131]
Related: https://wordpress.org/support/topic/comments-not-working-after-update/

Some reports say, Antispam Bee doesn't work no more, and you run into the WP message the comment field was left empty.

One part of this problem is caching. You will need to flush the cache to run 2.7.0 properly. But this didn't solve it for every reporter. We do have a problem in our secret generation as we rely on `get_the_title()` which provides an filter to manipulate the title. We need to be sure our comment-field-name-generation outputs the exact same outcome in the `init`-Filter and the `template-redirect`-action, but a filter flow like the following is not unlikely:

```
add_action( 'init', function() {
    add_filter( 'get_the_title', function( $title ) {
        return preg_replace( 'this', 'bythat', $title );
    }
}
```

To stabilize the outcome, we should switch to the posts ID in generating the secrets.

Furthermore, I want to investigate, what chars can be the real outcome of `sha1`. If it can be for example an `"` this might produce a problem as well. So, it might be a good idea to make sure to return only `a-z0-9` from the functions.

I will prepare an PR quickly.

**Comment by websupporter** [comment]
For documentation: currently working hotfix
```
<?php
/**
 * Plugin Name: Antispam Bee - Secret Generator
 * Description: Generate your own Antispam Bee secrets.
 **/

/**
 * Generates a new name for the textarea.
 *
 * @param string $secret The secret.
 * @return string
 **/
function ab_get_static_name_secret( $secret ) {

	return '43fgsg-daf';
}

/**
 * Generates a new id for the textarea.
 *
 * @param string $secret The secret.
 * @return string
 **/
function ab_get_static_id_secret( $secret ) {

	return '78dfmgdxdw';
}

add_filter( 'ab_get_secret_name_for_post', 'ab_get_static_name_secret' );
add_filter( 'ab_get_secret_id_for_post', 'ab_get_static_id_secret' );
```

**Comment by chesio** [comment]
> Furthermore, I want to investigate, what chars can be the real outcome of sha1. If it can be for example an " this might produce a problem as well. So, it might be a good idea to make sure to return only a-z0-9 from the functions.

If [sha1](http://at1.php.net/manual/en/function.sha1.php) function is used without the additional parameter set to true, then the string returned contains only hexadecimal characters ([a-f0-9]).

**Comment by websupporter** [comment]
Hi @chesio,
thanks for following up on this :+1:

I've created a PR, which simply removes `get_the_title()`
