### ISSUE TITLE
Improve RTL compatibility

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/antispam-bee#133]
As described in this [Form Thread](https://wordpress.org/support/topic/left-10000000px/) our absolute positioned textarea causes some trouble - a horizontal scrollbar - with RTL languages (in this example Hebrew). 
I'm pretty sure, this problem is partially caused by the theme, but we should be able to fix, by applying `right: -10000000px;` instead of `left: -10000000px;` when `is_rtl()` returns `true`.

**Comment by Zodiac1978** [comment]
Although we don't want to be accessible for screen readers with this hidden textarea we maybe could use the approach from the `screen-reader-text` class:
https://codex.wordpress.org/CSS#WordPress_Generated_Classes

See this review for some approaches:
https://snook.ca/archives/html_and_css/hiding-content-for-accessibility

For our method it states:

>In this case, if you have focusable content within the positioned element, the page will scroll to that element, thus creating an unsettling jump for sighted users.

**Comment by websupporter** [comment]
Not an expert, but since we have `aria-hidden="true"`, I think, we do not worry about screen readers? But I would be happy, if someone with more insight could verify this.

**Comment by websupporter** [comment]
fixed with #136
