### ISSUE TITLE
readme for 2.7.1

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#141]
We need to update the readme to 2.7.1

We fixed some bugs like
- fix some incompatibilities with other plugins (aka #131 )
- fix some incompatibilities with some browser settings (aka #130)
- support for RTL (#133)

Basically bugfixing for 2.7.0. Did I miss something?

**Comment by Zodiac1978** [comment]
If I look at the changes:
https://github.com/pluginkollektiv/antispam-bee/compare/2.7.0...master

we could summarize the third point to: "Fix: Solve some translation/language issues"
(textdomain, make langs translatable, fix typo, etc.)

**Comment by websupporter** [comment]
solved with #150
