### ISSUE TITLE
autocomplete=off does not help on Chrome

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#142]
I had the chance to test our master branch a bit and unfortunately `autocomplete=off` is simply ignored by Chrome.

> we started ignoring autocomplete=off for Chrome Autofill data

https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164

The proposed solution:

> In cases where you really want to disable autofill, our suggestion at this point is to utilize the autocomplete attribute to give valid, semantic meaning to your fields. If we encounter an autocomplete attribute that we don't recognize, we won't try and fill it.

or as MDN puts it:
> autocomplete="nope"

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by schlessera** [comment]
Ridiculous! (Google Chrome, not you, @websupporter)

**Comment by websupporter** [comment]
:joy:
