### ISSUE TITLE
`preg_replace_callback` does not work if textarea is prefilled.

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#147]
Example:
`<textarea name="comment">Comment here...</textarea>`

We do not catch such a `textarea` to replace it with our textarea.

@Zodiac1978 reported this for this framework: https://github.com/CherryFramework/CherryFramework/blob/master/comments.php#L73

I just got the same issue for another theme. Should we handle this edge case? So far, we concluded in Slack not to support this Edge case, but maybe it is not so rare as we figured?

**Comment by websupporter** [comment]
My reported case:

```
comment_form( array('fields'=>$fields, 'comment_field' => '<textarea id="comment" name="comment" maxlength="500" class="pbtheme_dark_border textarea_field block" aria-required="true">' . __( 'Your message goes here (max 500 chars)', 'pbtheme' ) . '</textarea>', 'title_reply' => do_shortcode('[pbtheme_title align="left"]'.__( 'Leave a comment', 'pbtheme' ).'[/pbtheme_title]'), 'title_reply_to' => __( 'Leave a Reply to %s' , 'pbtheme' ), 'label_submit' => __( 'Send comment', 'pbtheme' )));
```

**Comment by websupporter** [comment]
The related regex:
```
'/(?P<all>                                                              (?# match the whole textarea tag )
				<textarea                                                           (?# the opening of the textarea and some optional attributes )
				(                                                                   (?# match a id attribute followed by some optional ones and the name attribute )
					(?P<before1>[^>]*)
					(?P<id1>id=["\'](?P<id_value1>[^>"\']*)["\'])
					(?P<between1>[^>]*)
					name=["\']comment["\']
					|                                                               (?# match same as before, but with the name attribute before the id attribute )
					(?P<before2>[^>]*)
					name=["\']comment["\']
					(?P<between2>[^>]*)
					(?P<id2>id=["\'](?P<id_value2>[^>"\']*)["\'])
					|                                                               (?# match same as before, but with no id attribute )
					(?P<before3>[^>]*)
					name=["\']comment["\']
					(?P<between3>[^>]*)
				)
				(?P<after>[^>]*)                                                    (?# match any additional optional attributes )
				><\/textarea>                                                       (?# the closing of the textarea )
			)/x'

**Comment by 2ndkauboy** [comment]
Catching a textarea with prefilled Text makes sense. We should change the regex to match those. Let me try to get a regex for that.

**Comment by 2ndkauboy** [comment]
What's the status of this PR? Why was it not yet merged? Are their any edge cases we have to fix? Or do we want to write tests for it before merging?

**Comment by websupporter** [comment]
Reading through the PR:

We grab the whole HTML and run it through the regex. We are not in the comment_form_fields-filter (do not really recall its name right now). So edge cases to me are like "What about other textareas in the HTML like for example here: https://regex101.com/r/7Ywc6M/1

This is, what makes me really afraid of this PR. I think it would be great, if with this PR we also use the correct filter for the comment form.

**Comment by 2ndkauboy** [comment]
Unfortunately, there is no filter you can use to alter the HTML of the comment form, as it is echoed directy.
https://core.trac.wordpress.org/browser/tags/4.9/src/wp-includes/comment-template.php#L2170

But I think I found a regex that would match any content, even with the `<` sign, but not the cloaing `</textarea>` tag: https://regex101.com/r/7Ywc6M/3
