### ISSUE TITLE
Disable spam-notification-email by default.

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#151]
Notify the admin via email about incoming spam is set to true by default. The idea of ASB is to not be bothered by spam and now we find the spam and "spam" the admins mailbox by default. I would suggest to disable this feature by default.

You might want to get notified about comments ASB has classified as spam, because it might be a false positive, but should it be enabled by default?

Ref.: https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L387

**Comment by 00travelgirl00** [comment]
I totally agree and just wanted to open the same ticket!

**Comment by 00travelgirl00** [comment]
Maybe we can could add this ticket to #110?

**Comment by Zodiac1978** [comment]
Sergej explained this in this way: it is enabled by default to check the results in the first time. After this you can disable it.
