### ISSUE TITLE
autocomplete="off" instead of "nope"

### ISSUE THREAD

**Issue by drjs** [pluginkollektiv/antispam-bee#155]
Currently, for textarea the code uses autocomplete="off" instead of "nope". This leads to unnecessary HTML violations.
Replacing "nope" with "off" in lines 1300 and 1311 of antispam_bee.php fixes this.
Thanks
Joachim

**Comment by Zodiac1978** [comment]
That is intentionally. Please see this Issue for more details:
#142

**Comment by drjs** [comment]
Oh, I see, sorry for bothering then. So, the validation may be a bit too strict here...
