### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#156]
With PHP 7.2 beta 1 released (http://php.net/archive/2017.php#id2017-07-20-1), we should start to update some parts of our code.

**Comment by websupporter** [comment]
This means getting rid of `create_function()`

http://php.net/manual/en/function.create-function.php

**Comment by stklcode** [comment]
Don't forget that this implies bumping the _PHP 5.2.4 or greater_ to at least 5.3. Presumably not a big loss :smile:

**Comment by websupporter** [comment]
Thanks, maybe we shouldn't use anonymous functions than :thinking:

**Comment by stklcode** [comment]
Hmm, looks like we actually don't do this, despinte in one test class. So we're might still be fine with 5.2 (think so, my current IDE doesn't support it anymore). Declaring the function explicitely and adding `array(...)` twice and we're also fine with 5.2 for testing.

Btw. Travis doesn't even support 5.3 in trusty environments which become default by now.

**Comment by websupporter** [comment]
Yes :joy:

Well, in my PR I replaced https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L2213 with an anonymous function. Not sure yet.

**Comment by chesio** [comment]
Personally, I'm for dropping support for PHP 5.2 (and maybe PHP 5.3 as well) despite that it does not seem that WordPress core is going to drop support for these ancient PHP versions soon.

But at least there's now an initiative to make plugin authors' life easier by letting them declare [required minimum PHP version](https://core.trac.wordpress.org/ticket/40934).

**Comment by stklcode** [comment]
I would not drop, until necessary - right bow it isn't.

If a new feature requires or is easier to implement with 5.4+ code, go for it and bump the support, but not because of test sources or because we want.

**Comment by websupporter** [comment]
Merged in #157
