### ISSUE TITLE
Correctly translate the readme file

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/antispam-bee#16]
If we want, we can translate the complete readme file on WordPress.org. No need for a "Auf Deutsch?" hint in the readme anymore perhaps.

**Comment by glueckpress** [comment]
:+1: Cool, how would that work? It’s not imported into GlotPress yet, is it?

**Comment by Zodiac1978** [comment]
It is: https://translate.wordpress.org/projects/wp-plugins/antispam-bee/

**Comment by glueckpress** [comment]
:tada:

**Comment by swissspidy** [comment]
The "Auf Deutsch" note could be removed though, as initially stated. I know that it's on dotorg

**Comment by glueckpress** [comment]
Posting this as a note to self here:

> For a language pack to be generated (for stable or development), the project needs to be at 100%. But for the readme project(s), each string will go out when it’s translated. There’s a delay due to caching, so it’s not ​_immediate_​ but it happens pretty fast.
https://wordpress.slack.com/archives/polyglots/p1449062835001560

**Comment by swissspidy** [comment]
Let's keetp the "Auf Deutsch" note for now as it works well the way it is at the moment.
