### ISSUE TITLE
Design should be more Accessible 

### ISSUE THREAD

**Issue by 00travelgirl00** [pluginkollektiv/antispam-bee#162]
The fonts are pretty small and the color contrast does nit match the AA standard. Also the links are not underlined, which makes it hard for color blind people. 

For a better user experience I suggest to solve this problems. 

I have made a PR for that: #161 
<img width="1276" alt="bildschirmfoto 2017-11-20 um 23 03 05" src="https://user-images.githubusercontent.com/21318377/33103847-ce1b406a-cf1c-11e7-9993-3afbfc0974c6.png">

**Comment by krafit** [comment]
@00travelgirl00 and I decided to close this PR for now and open a new a11y related pull request for the upcoming Antispam Bee version :)
