### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#166]
From the PHP compatibility checker plugin:

> FILE: /wp-content/plugins/antispam-bee/antispam_bee.php
> --------------------------------------------------------------------------------------------------
> FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
> --------------------------------------------------------------------------------------------------
>  2213 | WARNING | Function create_function() is deprecated since PHP 7.2; Use an anonymous function instead
> --------------------------------------------------------------------------------------------------

Should we change something?

**Comment by websupporter** [comment]
hi @Zodiac1978 

should be already solved in `master` with https://github.com/pluginkollektiv/antispam-bee/pull/157 and https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L2213

**Comment by Zodiac1978** [comment]
Great! I think we can close this then.
