### ISSUE TITLE
Add GDPR compliance notice

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/antispam-bee#167]
The EU General Data Protection Regulation will be in full force from 25th of May 2018 - lets make it super clear to users, if any part of their ASB config is violating GDPR.

I'm pretty sure about 90% of all ASB options are GDPR compliant (except external spam DBs and maybe the Google Language API) so this is issue is more about some interface tweaks to guide users rather than actually changing GDPR compliance, but #154 might benefit this.

**Comment by mundschenk-at** [comment]
What about saving/using the IP address?

**Comment by websupporter** [comment]
Hi @mundschenk-at,
Antispam Bee is not saving the IP address, but WordPress core does. This plugin should prevent WP from saving the IP: https://de.wordpress.org/plugins/remove-ip/

**Comment by mundschenk-at** [comment]
Yes, I know. But ASB is still processing the IP, so that touches GDPR. Before reviewing the code, it was not entirely clear to me in what way not storing the IP (e.g. via Remove IP) would impact ASB. This is something that should be documented, as removing or anonymizing the comment IP will become more common in the next frew months.

**Comment by 2ndkauboy** [comment]
If the commenter's IP address is not stored, the local spam DB would not work anymore. But the other tests should still work.

**Comment by websupporter** [comment]
```

**Comment by websupporter** [comment]
```
		$filter = array('`comment_author_IP` = %s');
		$params = array( wp_unslash($ip) );

		// Match the URL
		if ( ! empty($url) ) {
			$filter[] = '`comment_author_url` = %s';
			$params[] = wp_unslash($url);
		}

		// Match the E-mail
		if ( ! empty($email) ) {
			$filter[] = '`comment_author_email` = %s';
			$params[] = wp_unslash($email);
		}

		// Perform query
		$result = $wpdb->get_var(
			$wpdb->prepare(
				sprintf(
					"SELECT `comment_ID` FROM `$wpdb->comments` WHERE `comment_approved` = 'spam' AND (%s) LIMIT 1",
					implode(' OR ', $filter)
				),
				$params
			)
		);
```
it would still check on email and url for incoming comments.
