### ISSUE TITLE
Add padding: 0 to inline styles?

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#168]
https://wordpress.org/support/topic/bug-report-2-7-1-messing-up-viewport-breaks-mobile-layout/

**Comment by websupporter** [comment]
Hi @Zodiac1978,
I can confirm for Chrome. If you disable his workaround, the horizontal scroll-bar starts to show up. A inline `padding:0` seems to fix this issue. So I am 👍
