### ISSUE TITLE
Add filter for notification email to allow multiple recipients

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#173]
First requested here:
https://wordpress.org/support/topic/send-comment-spam-notification-to-different-second-user/#post-10044070

Relevant code:
https://github.com/pluginkollektiv/antispam-bee/blob/b571e5df7d2efbb53eca10c985347efb266ea349/antispam_bee.php#L2505-L2515

`wp_mail` is supporting multiple recipients in an array or comma separated:
https://developer.wordpress.org/reference/functions/wp_mail/

Interesting feature? Filter okay? UI needed?

Feedback welcome! :)

**Comment by websupporter** [comment]
Hi @Zodiac1978,
in my eyes, we can add a filter, something like 
```
apply_filters (
    'antispam_bee_notification_receipiants',
    get_bloginfo( 'admin_email' )
),
```

But I wouldn't push this feature into the UI. I don't think it is that important, as I think the whole idea of sending emails with "spam notifications" is somewhat against the principal idea of a antispam plugin and is probably only useful to check a bit, if the plugin is working. But other users might have better use cases for it.

**Comment by Zodiac1978** [comment]
@websupporter Agree on all points. :) 

How would this work in practice?

Is this correct?

Comma separation:
`
function add_email_recipients( $recipients ) {
  $recipients .= ', test@example.org'; 
  return $recipients;
}
add_filter( 'antispam_bee_notification_recipients', 'add_email_recipients' );
`

Array:
`
function add_email_recipients( $recipients ) {
  $recipients[] = $recipient;
  $recipients[] = 'test@example.org'; 
  return $recipients;
}
add_filter( 'antispam_bee_notification_recipients', 'add_email_recipients' );
`

**Comment by websupporter** [comment]
Hi @Zodiac1978 ,
actually, seeing this, I think, we should make sure, to use only one type. What I mean is in your second example, `$recipient` could be an array, but you do not check against it. I would suggest, we do actually use array from the beginning:

```
/**
 * Filters the recipients of the spam notification
 * @param array The recipients array.
 **/
apply_filters (
    'antispam_bee_notification_recipients',
    array( get_bloginfo( 'admin_email' ) )
),
```

This way it would make clear (and the filternaming would fit more properly), we expect 1 or more recipients.

But now, actually, both examples wouldn't work :sweat_smile: These would be two working examples:

```
function add_email_recipients( $recipients ) {
  $recipients[] = 'add_another@recipient.com'; 
  return $recipients;
}
add_filter( 'antispam_bee_notification_recipients', 'add_email_recipients' );
```

```
function new_email_recipients( $old_recipients ) {
  $new_recipients = array('new@recipient.com'); 
  return $new_recipients;
}
add_filter( 'antispam_bee_notification_recipients', 'new_email_recipients' );
```

**Comment by Zodiac1978** [comment]
Looks much better! :)

**Comment by websupporter** [comment]
I will prepare a PR today or tomorrow.
