### ISSUE TITLE
Use https for stopforumspam.com

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#175]
Stopforumspam is supporting http and https with their API (https://stopforumspam.com/usage)

Se we should change this link to https:
https://github.com/pluginkollektiv/antispam-bee/blob/b571e5df7d2efbb53eca10c985347efb266ea349/antispam_bee.php#L1825

Or are there any reasons to stick with http here?

**Comment by websupporter** [comment]
no, we should switch. :+1:
