### ISSUE TITLE
Change title for blocking feature for more clarity

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#178]
At the moment the feature has the description:
**Block comments from specific countries**

We do allow whitelisting too and although this means blocking for the rest, we could change the title for more clarity to
**Block or allow comments from specific countries**

First reported here:
https://wordpress.org/support/topic/allow-many-languages/

**Comment by websupporter** [comment]
The string, we need to change:
https://github.com/pluginkollektiv/antispam-bee/blob/master/inc/gui.class.php#L302

**Comment by websupporter** [comment]
closed via #186
