### ISSUE TITLE
Add IPv6 support

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/antispam-bee#19]
See https://wordpress.org/support/topic/check-for-a-fake-ip-not-working-correctly-with-ipv6?replies=2

**Comment by glueckpress** [comment]
+1

**Comment by schlessera** [comment]
IPv6 support can be disabled during PHP runtime compilation.

The constant `AF_INET6` can be checked to know whether the current PHP build supports IPv6 addresses or not (see http://php.net/manual/en/sockets.constants.php).

I'm not 100% what exact this has on how IPv6 addresses are internally handled, but it is something to keep in mind.

**Comment by websupporter** [comment]
In WordPress the `REQUEST` package has a `Requests_IPv6` class where you can validate. But I am not sure since which WP version and I guess it is not 3.8. Maybe we can have a look there. But there it isa bit more of a complex operation though.

**Comment by MrFly** [comment]
It would be great to deactivate the IP check seperately for IPv4 and IPv6 at the plugin settings. This would us (users) give a nearly perfect tagging for IPv4 and would us not give that many false-positives for widely unsupported IPv6 from hosters.

**Comment by Zodiac1978** [comment]
It is more likely that we remove this check completely. We can't rely on IPv6 support in PHP and load balancer can produce false positives too. In our tests this check is producing false positives only.

**Comment by websupporter** [comment]
Closing this issue in favor of #304 to centralize the discussion there.
