### ISSUE TITLE
Spam reason description

### ISSUE THREAD

**Issue by toxicdemonWP** [pluginkollektiv/antispam-bee#192]
In the email message, the spam reason is „CSS-Hack“. This is very misleading. As specially for customers without deep knowledge background. 

It might make sense to switch it to „CSS-trap“ or something like that.

**Comment by krafit** [comment]
I talked to @toxicdemonWP about this at WordCamp Retreat Soltau today. And I agree, even thou  never heard of the problem before. To an unexperienced user the term "hack" has something bad to it, changing it would not hurt anybody and could avoid some irritation in the future.

**Comment by krafit** [comment]
So the question is, what should we call it?

**Comment by KittMedia** [comment]
I would suggest `honeypot` because that’s what it actually is.

**Comment by websupporter** [comment]
I am in favour of honeypot. Since its an Antispam _Bee_, it would fit into the naming I think :)

**Comment by toxicdemonWP** [comment]
As x just said, it sounds even more likely ;-) Then 
I think the bee gets a honeypot. sounds good. 

FYI: all this time I thought of the German translation, hence my idea of the "trap".

**Comment by Zodiac1978** [comment]
Yes, `honeypot` sounds correct in every manner. :)
