### ISSUE TITLE
css/styles.min.css doesn't reflect changes in css/styles.css

### ISSUE THREAD

**Issue by pixolin** [pluginkollektiv/antispam-bee#196]
According to the git change message, file styles.css was changed to _"replace icon font with Dashicons"_ but it seems the file wasn't minified. The result is, that the dashicon can't be loaded in the WordPress back end. (Screenshot: https://i.imgur.com/JTayGEX.png)

**Comment by krafit** [comment]
you are absolutely right, thanks for catching this ❤️
