### ISSUE TITLE
Kleine Anpassung in der Doku / Wiki

### ISSUE THREAD

**Issue by ginocremer** [pluginkollektiv/antispam-bee#198]
Unter https://github.com/pluginkollektiv/antispam-bee/wiki/de-Dokumentation#kommentare-nur-in-einer-sprache-zulassen habt ihr in der Doku notiert: "Zur Ermittlung der Sprache wird Google Übersetzer genutzt. Dabei überträgt Antispam Bee den Kommentartext an den Online-Dienst." - Nur zur Präzisierung vielleicht hinzufügen, dass nur die ersten drei Wörter übertragen werden. Kleinigkeit, aber wichtig in Zeiten der DSGVO/GDPR.

**Comment by websupporter** [comment]
Actually, its the first 10 words
`$query_text = wp_trim_words( $comment_text, 10, '' )`

**Comment by ginocremer** [comment]
OK, I'll ask Simon Kraft to change his blog post. He told about sending just three words out to Google.

**Comment by krafit** [comment]
Oh, we always talked about 3 words, I‘ll change my post accordingly

**Comment by websupporter** [comment]
Just wanted to leave this comment, so we get this correct in the wiki. I didn't look it up when I read @krafit blog post, otherwise, I would... . Thanks for your suggestion :smile:

**Comment by krafit** [comment]
I updated the wiki (en/de) to explicitly note, only the first 10 words are sent to Google.
