### ISSUE TITLE
Make links translatable

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#199]
If we make these two links translatable we could switch theme to the localized versions:

https://github.com/pluginkollektiv/antispam-bee/blob/issue-191/inc/gui.class.php#L508

and 

https://github.com/pluginkollektiv/antispam-bee/blob/issue-191/inc/gui.class.php#L511

**Comment by Zodiac1978** [comment]
We already do this:
https://translate.wordpress.org/projects/wp-plugins/antispam-bee/stable/de/default?filters%5Bterm%5D=wordpress.org&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

For the wiki this would work, but the other link could be every language provided from WP.

We could use the language from the profile or site ...

**Comment by websupporter** [comment]
Actually, I think it would be a good thing to have them translatable and I would suggest to go the path, we already have laid out (as @Zodiac1978 points out).

**Comment by websupporter** [comment]
just to verify, as the original links here haven't been stable, those are the links in question, right?
https://github.com/pluginkollektiv/antispam-bee/blob/752046a0248b5334503667bc8927751e2743e983/inc/gui.class.php#L526-L529

**Comment by krafit** [comment]
👍

**Comment by Zodiac1978** [comment]
@websupporter As we just have the wiki in EN or DE we could use the idea from @krafit in this comment https://github.com/pluginkollektiv/antispam-bee/issues/199#issuecomment-390905636 to show the German or English one.

The second link is to wordpress.org, so there are much more choices (all locales from wp.org), so the translation makes sense.
