### ISSUE TITLE
Add option to blacklist top level domains

### ISSUE THREAD

**Issue by kevinpapst** [pluginkollektiv/antispam-bee#2]
Since the feature "filter by country" was removed, wouldn't it be possible to filter incoming comments by top level domains or even better by substrings of the FQDN?
For example I receive regular spam from a dynamic dial in address in china, which looks like this: 59.174.xx.yyy, xxxxxxx.dynamic.163data.com.cn

Right now the spam passes all of Antispam-Bees filters. But if I could add a search string for the commenting IP like ".cn" or even "dynamic.*.com.cn" that would help me ease the pain with these spam comments, which unfortunately are not catched by the existing filters.

What do you think?

**Comment by glueckpress** [comment]
Not sure about statistics here. Are top-level domains generally relevant as a parameter? I’m leaving this open for discussion for the time being, but personally I think if we do anything on the geo side we should aim to bring the filter by country feature back to ASB.

**Comment by kevinpapst** [comment]
I checked a lot of my spam the last days and throughout several blog. From this very small statistic it seems only a minor amount of all IPs can be resolved to a hostname. So your solution would be much better.

**Comment by glueckpress** [comment]
@kevinpapst Thanks, I’m going to close this issue then as _wontfix_. A possible revival of the country filter feature is being discussed anyhow, i.e. we’re keeping an eye on the demand.

**Comment by kevinpapst** [comment]
Thanks for looking into it nevertheless. 
Seems that this request has not a huge demand as nobody ever commented ;-)

**Comment by glueckpress** [comment]
Probably. :wink:  
Btw, out of pure curiosity: In what way does the comment blacklist field at /wp-admin/options-discussion.php not solve the issue you described?

**Comment by kevinpapst** [comment]
Very good question. I didn't even knew about that configuration before you mentioned it ;-)
Actually all the spam on all of my sites is very effectively filtered by AntiSpam-Bee. 
Out of all the thousands of Spam I receive regularly, this was the very first automated spam which was able to bypass the Bee ...  so I never even thought about given this a try. But I'll try it the next time!
