### ISSUE TITLE
min wp version

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#205]
The min wp version is 4.5 now, but we state 3.8

**Comment by krafit** [comment]
I'm not sure, if I really like lifting the min version this much,  but on the other hand: if your WP is still 3.8 you are probably not updating ASB either 😂

**Comment by websupporter** [comment]
yes and as it slipped through this time, we should really require a quite "late" min version. 4.5 seems quite fine to me.
