### ISSUE TITLE
Version 2.8.0 not compatible with PHP 5.3.x

### ISSUE THREAD

**Issue by benderl** [pluginkollektiv/antispam-bee#208]
My webhoster still uses PHP in Version 5.3.x and I am not able to upgrade. After updating antispam-bee I got an error 500 when going to the antispam-bee settings. Please replace the brackets '[]' in lines 40 and 42 of gui.class.php with 'array()' and your plugin will work even with PHP 5.3.x.

https://github.com/pluginkollektiv/antispam-bee/blob/045b9f2dc3d896d87eb6369b61a8fd88e0f5eccd/inc/gui.class.php#L42

**Comment by benderl** [comment]
Please have a look at #209.

**Comment by websupporter** [comment]
Hi @benderl,
thanks a lot for your pull request. not used any more to `array()`, I am very sorry. This is now merged in master and will be in the upcoming version `2.8.1` which will be released soon.

Sorry again for the trouble.
