### ISSUE TITLE
Re-add language check

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/antispam-bee#21]
…using Google's API

**Comment by kreativmonkey** [comment]
I'm searching for a other methode to detect language without pay for the API. Paying is no Problem for big projects but for small private blogs. My personal favorid solution is a local script to detect language. No API, no pay and privacy is protected. 

https://github.com/BruceJillis/PHP-Language-Detection/blob/master/etc/NGram%20Language%20Detection.pdf

**Comment by swissspidy** [comment]
Thanks for the link, @kreativmonkey! Looks interesting, but I don't see that one being built into the plugin itself. Could make for a nice add-on though. Will definitely play with it a bit.

**Comment by swissspidy** [comment]
Closing in favour of #31
