### ISSUE TITLE
Self-Pingbacks and Fake IP

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#212]
What happens, if the "Fake IP"-check is active and a blog post of my blog pings another blog post of the same blog. Wouldn't this result in a "Fake IP" and is there a way to prevent this behavior?

Related: https://wordpress.org/support/topic/verwirrt-uber-pingbacks/

**Comment by krafit** [comment]
🤔 
There is a way to automatically approve self-pingbacks, so it should be possible to identify them and do some sort of whitelisting on them.

**Comment by websupporter** [comment]
Actually, if I send a pingback to one of my posts, this pingback is treated like every other pingback. But I should be able to trust myself. I should be able to post about "Viagra" without running  into the regex filter. I should be able to write a Russian post and not run into the language check and so on.

**Comment by krafit** [comment]
🇷🇺 🇨🇳 💯
