### ISSUE TITLE
Spam trackbacks not detected as spam

### ISSUE THREAD

**Issue by florianbrinkmann** [pluginkollektiv/antispam-bee#213]
Hey,

first, thanks for your work! ❤

For a week or so, I get many spam trackbacks on my site that are not detected as spam by Antispam Bee. They are all written with the same pattern: One line in bold, that is the same as the commenter name, and then one additional sentence (see the screenshot). The weird thing: there are also many trackbacks with that pattern that are marked as spam correctly.

![antispam-bee-false-negatives](https://user-images.githubusercontent.com/2310924/40599349-0897a1e8-624d-11e8-9d29-45a0f84b5fba.png)

At first I thought that may be related to #203, but 2.8.1 did not fix it.

Any idea what the reason could be? I disabled saving the IP adresses with the snippet by @krafit: https://gist.github.com/krafit/ff7678ee6d095a5e861ea3bb3c5b50c6 
Would it be helpful if I enable saving the IP adresses temporarly again and report a set of IP adresses from the trackbacks that were not detected as spam?

Thanks in advance,
Florian

Edit: Don’t know if it helps, but: the issue occurs on a multisite.

**Comment by websupporter** [comment]
Hi @florianbrinkmann,
thanks for your request. The pattern you are discovering is the default WordPress markup for trackbacks (https://core.trac.wordpress.org/browser/trunk/src/wp-trackback.php#L125), whereby the blog_name and the title of the trackback are equal. Actually, this could be a nice indicator for spam.

> For a week or so,

**Comment by florianbrinkmann** [comment]
Hey @websupporter,

cool, thanks a lot! Regarding #222 – if it helps to find patterns, I could provide many, many spam comments for analyzation :D

**Comment by websupporter** [comment]
Hi @florianbrinkmann,
actually, we :heart: spam.

We use [this google doc](https://docs.google.com/spreadsheets/d/1IJWa8nBlGasJhJbA3fvGnh-QPt4EhGTA9w5eZByGYs0/edit#gid=260223063) to collect it, so spam us.

:see_no_evil:

**Comment by florianbrinkmann** [comment]
Hey @websupporter,

okay cool :) Currently, the rate of not-detected trackbacks is very low again (no one in the last few of days if I remember correctly). I will look into my email trash folder for the »please moderate« emails for the the not-detected spam trackbacks and add them to the doc :)

**Comment by florianbrinkmann** [comment]
The Spam is back :D Maybe had only a weekend pause ^^

**Comment by websupporter** [comment]
Hi @florianbrinkmann,
today I've merged some of the issues into `dev-master`.

Given the pattern you have detected is still the same in your incoming spam wave, the current `dev-master` should be able to detect the spam.

Given some trackbacks still come through but you mark them as spam by yourself, this should now stop trackback spam from the same IP.

So, if you are brave enough to give the `dev-master` a chance, it would be wonderful, if you could give it a try :heart:

**Comment by websupporter** [comment]
Ah, and sorry, I linked the wrong Google doc. Actually we have a form, where you can submit spam:
https://docs.google.com/forms/d/e/1FAIpQLSeQlKVZZYsF1qkKz7U78B2wy_6s6I7aNSdQc-DGpjeqWx70-A/viewform?c=0&w=1

**Comment by florianbrinkmann** [comment]
There was not much trackback spam since I installed the `master` – will keep you updated :)

**Comment by florianbrinkmann** [comment]
I had many spam trackbaks in the last days again, all marked as spam correctly, so: looks very good, thanks a lot! :)

**Comment by websupporter** [comment]
Super cool! :tada: 

Thanks for the feedback @florianbrinkmann
