### ISSUE TITLE
evaluate if we can use wp_privacy_anonymize_ip

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#215]
With WP 4.9.6 a new function came into WordPress core: `wp_privacy_anonymize_ip()`. Lets see, if we can utilize this function instead of our own anonymizer, when we send the anonymized IP to detect the origin country

**Comment by krafit** [comment]
Would be additional anyways, wouldn't it? While supporting WP versions <4.9.X we need a kind of fallback for this.

**Comment by websupporter** [comment]
@krafit , right, didnt think about this. thats a showstopper for me. thanks for your feedback.
