### ISSUE TITLE
Extend regex check

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#222]
again about this fruitful #213 issue:

maybe 
"purchase amazing ..." and "buy amazing ..." should be regarded as regex spam?

**Comment by websupporter** [comment]
any feedback on these two strings, otherwise i would add them?

**Comment by krafit** [comment]
go for it :)

**Comment by Zodiac1978** [comment]
I can't see this matching any of our not-detected spam in our spreadsheet. On which data grounds this?

**Comment by websupporter** [comment]
See the picture in #213
