### ISSUE TITLE
Support webmention type

### ISSUE THREAD

**Issue by dshanske** [pluginkollektiv/antispam-bee#224]
Webmentions aren't in WordPress Core, and exist only as a plugin. Spam webmention are not a thing yet, hopefully never. 

Webmentions are a W3C Specification and a modern successor to pingbacks. 

The only real thing Antispam Bee needs to do is be aware of the webmention comment type.

**Comment by krafit** [comment]
Hi @dshanske,

thanks of submitting this, I really like the idea. We'll take a look at it :)

**Comment by websupporter** [comment]
The mentioned plugin to have a look https://wordpress.org/plugins/webmention/

**Comment by websupporter** [comment]
I had a look into this plugin. I will move this request to Future Release. Currently, to support webmentions, we need to restructure a lot of our plugin. As the plan is anyway to do so in ASB3.0, which would make our plugin much more flexible, I think we should revisit this request afterwards.
