### ISSUE TITLE
Raphaël does not work when CSP disallows 'unsafe-eval'

### ISSUE THREAD

**Issue by abrain** [pluginkollektiv/antispam-bee#231]
The version of Raphaël used in this plugin does not work on pages with a Content Security Policy disallowing `unsafe-eval` for [script-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src). This was fixed in Raphaël version [2.1.2](https://github.com/DmitryBaranovskiy/raphael/blob/master/history.md#212--2015-08-26).

(see https://github.com/pluginkollektiv/statify/issues/52)

**Comment by krafit** [comment]
Hi @abrain - thank you for reporting this issue - you seem to be in the wrong plugin though. This is Antispam Bee - please open this issue again in the Statify repo :)

**Comment by abrain** [comment]
I linked the Statify issue, as it is the exact same problem and has been solved there. Antispam Bee still has this problem. ;)
