### ISSUE TITLE
Reevaluate "Comment form used outside of posts" option

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#235]
![grafik](https://user-images.githubusercontent.com/6458412/41822649-b7c8e8a2-77fb-11e8-898c-e27f11747572.png)

I am not quite sure, but I think, this option would currently be broken. If so, I can't remember any feedback about this option being broken, so we should simply get rid of it.

I will have a look, if it works, but I am like 90% sure it doesn't. 

What do you think?

**Comment by websupporter** [comment]
When I add `comment_form()` to an archive page like

```
while (have_posts) :
    the_post(); 
    //stuff
    comment_form();
endwhile;
```

and set the option, this option does not work as expected:

only the first article works properly.

reasons:
* the regex to insert the honeypot works only on the first comment form element.
* i guess, even if this would work, the 2nd problem would be i guess the way, we construct the textarea name for our comment field. it takes the post ID into account and assumes to be on a single post while doing so.

Actually, this was reported here: https://wordpress.org/support/topic/comment-form-used-outside-of-posts-not-working-properly/ but somehow we missed/forgot about it.

What do you think would be the best way to proceed. Prior to my finding in the support forum I thought, well nobody complained yet, so get rid of the option, but the option at least seemed to be in used 1.5 years ago (I guess by now... not any more).

**Comment by Zodiac1978** [comment]
> the regex to insert the honeypot works only on the first comment form element.

This is an easy fix and worked for the user.

> the 2nd problem would be i guess the way, we construct the textarea name for our comment field. it takes the post ID into account and assumes to be on a single post while doing so.

This is the main question here. Can we fix this? Any chance to use another method or use the IDs from the post list for each form? If not, yes, let's remove the feature completely. If yes, let's fix it.

**Comment by Zodiac1978** [comment]
Related: https://github.com/pluginkollektiv/antispam-bee/issues/128

**Comment by websupporter** [comment]
And I completely oversaw #128 :man_facepalming: 
> Can we fix this?
