### ISSUE TITLE
Fix compatibility issues with secret name in comment form

### ISSUE THREAD

**Issue by felixarntz** [pluginkollektiv/antispam-bee#242]
Antispam Bee currently adjusts the comment form to use different field names, so that those cannot as easily be figured out by spam bots. For that, it replaces the comment textarea ID and name with a generated secret.

This usually works fine, however it can cause compatibility issues with other plugins if those perform additional logic on the comment form: When the secret starts with a number and then the value of the ID or name attributes are used as properties in JavaScript, this is an issue because properties should not start with a number. A concrete example is the AMP plugin for which comment forms break because of that - every comment form where the secret starts with a number will throw a JavaScript error because of the `amp-bind` integration with the comment form it needs to handle.

I used a quick fix for myself by using the `ab_get_secret_name_for_post` filter (I was amazed there is a filter for something as granular as this! 💯), but it would help if the plugin would ensure on its own that the secrets always start with a letter.

**Comment by websupporter** [comment]
Hi @felixarntz,
I am in the middle of a release, but I schedule this for the next one. Thank you for the report!
