### ISSUE TITLE
Inconsistent dashboard tooltips

### ISSUE THREAD

**Issue by KittMedia** [pluginkollektiv/antispam-bee#248]
I currently use the Antispam Bee dashboard beside the Statify dashboard and could recognize an inconsistency in the dashboard tooltips of them.

The current tooltip of Antispam Bee:

<img width="103" alt="bildschirmfoto 2018-10-18 um 12 14 28" src="https://user-images.githubusercontent.com/1018979/47147839-63d88e80-d2cf-11e8-85b4-0d9b7fa2cc7a.png">

The current tooltip of Statify:

<img width="133" alt="bildschirmfoto 2018-10-18 um 12 14 34" src="https://user-images.githubusercontent.com/1018979/47147853-6e932380-d2cf-11e8-9310-e6074b92a813.png">

As you can see, Statify uses the long date version and the date before the actual data. I would recommend to use the same format for Antispam Bee.

So, instead of:
```
6× Spam
18.10.2018
```
I would suggest the following:
```
18. Oktober 2018
6 × Spam
```

Additionally to the row swap I would add an additional space between the number and the `×` sign as this would be typographically correct.

**Comment by krafit** [comment]
Nice catch, go ahead and open a PR, if you want to, @KittMedia 👍 
One thing thou: `6x spam` could be considered a symbolic notation, like `15°`. In this case, it's not allowed to insert a space.
