### ISSUE TITLE
Harmonize admin UI

### ISSUE THREAD

**Issue by glueckpress** [pluginkollektiv/antispam-bee#25]
I’d like to implement a couple of enhancements on ASB’s settings page, mostly to support fluid/responsive layout, varying font-sizes etc. As of today, the UI looks neat, but breaks when e.g. feature descriptions exceed a certain line number. 

Will make a list of specific enhancements soon. 
Also open for feedback. 
(Note: We’re talking about improving existing UI, not new features or anything. :wink: )

**Comment by Zodiac1978** [comment]
@timse201 @glueckpress Can we close this issue or should it stay open for more improvements?

I would like to release 2.7 soon.

**Comment by timse201** [comment]
the only thing i would like to do is to include the privacy notes into the descriptions
will do a pull request soon
but please note #49

**Comment by timse201** [comment]
after all this set i think it can be closed
the ui does not break translations anymore
the ui looks the same on mobile and desktop devices
and there are some advantages now like input number
