### ISSUE TITLE
Check for Gutenberg compatibility 

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/antispam-bee#250]
WordPress 5.0 will be here soon. Time for us to check, if our plugins are compatible with the Gutenberg Editor and WP 5.0 (a beta version is yet to be published). 

- [x] check (Gutenberg) editor with this plugin
- [x] check plugin settings site with active Gutenberg
- [x] fix potential issues
- [x] add `Tested up to: 5.0` to the plugins readme
- [x] publish changes as minor update or with upcoming plugin update

**Comment by florianbrinkmann** [comment]
I wrote a comment as not-logged-in user and logged in with active Antispam Bee and Gutenberg, and it works. Checked saving of the settings page and that seems to be working, too.

**Comment by krafit** [comment]
I can confirm, there's no issue with ASB and WP 5.0 so far (I'm running several installs without problems). As soon as we hit the first, 5.0 RC, I'll close this issue.

**Comment by websupporter** [comment]
merged with #252
