### ISSUE TITLE
Use PHPCompatibility Check for low PHP versions

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#255]
We are currently having trouble to check older PHP-versions for incompatibilities, while we have users, who still run our plugin on older PHP versions.

Underlying the PHP Compatibility Checker Plugin (https://wordpress.org/plugins/php-compatibility-checker/) is a PHP Codesniffer ruleset, which basically enables you to run static analysis on your code against specific PHP versions.

As far as I can see, we could also run PHP 5.2 checks.

Its not a 100% guarantee to not run into problems, but it would catch probably most of the common mistakes we might run into like using `array()` instead of `[]`
https://github.com/PHPCompatibility/PHPCompatibility

**Comment by 00travelgirl00** [comment]
Is this still neccessary, after WordPress 5.1 is released? 

https://wordpress.org/news/2019/01/wordpress-5-1-beta-1/

5.1 will include a Site Healt Check, where there will be a warning displayed if your PHP Version is lower than 5.6.

**Comment by 2ndkauboy** [comment]
I like the solution proposed in https://github.com/pluginkollektiv/antispam-bee/issues/216#issuecomment-393679218

Let the main plugin file check for a minimum PHP version. If this one is not available, just return and not load the plugin.

Sure it is not nice to break PHP compatibility for users with versions lower then e.g. 5.6, but as both PHP 5.6 and 7.0 have reached their end of support, we should at least require 5.6 as the minimum version.

**Comment by websupporter** [comment]
I think raising PHP version should be discussed in #216 or another issue. The topic of this issue is

"as long as we support php 5.x.x, we should have tests in place to make sure, we do not break this support by accident"

Of course, if we decide to not support below 5.6, this issue gets obsolete, as we have tests for 5.6+.

But lets keep the discussion focused at one ticket.

**Comment by 00travelgirl00** [comment]
I think we don't have to support a lower PHP Version, then WordPress supports.

**Comment by 2ndkauboy** [comment]
WordPress Core still supports 5.2 ;)

**Comment by 00travelgirl00** [comment]
@2ndkauboy oh sorry. so its just the warning for everything under than 5.6?

**Comment by websupporter** [comment]
@00travelgirl00 yes its a heads up for the next version, which then will require a higher PHP version. I did just find this proposal https://make.wordpress.org/core/2018/12/08/updating-the-minimum-php-version/, I am not quite sure about the current discussions, but should be something along those lines. In addition someone could make the case of the min. WordPress version ASB is going to support. You could build an argument for a lower PHP version from there I guess.

As I said in #216 I am all for raising the PHP version, if it benefits Antispam Bee and not just its developers. For me, this case must be made. With the recent events (min. Version of WP will soon be 7 and ASB will slowly raise the min version of WP it supports) there seems an automatism to a min PHP version just by the context ASB runs in.

But as for now: We could easily run our 5.2 (or 5.3, not sure)-code in a context, which has a minimum PHP version of 7.2 and just adapt where necessary, see #157. On the other hand raising the minimum version abandons users, see #208. Arguing for a raise of the PHP version without a _why_ (e.g. we could use interfaces and could make the spam filters pluggable in a neat way) is - in my eyes - for no good reason. The _why_ is basically ASB 3.0 and discussing this reminds me, I should just get started with 3.0 :laughing:
