### ISSUE TITLE
Email summary

### ISSUE THREAD

**Issue by thomastrethan** [pluginkollektiv/antispam-bee#26]
Instead of sending each spam entry as a separate email to the admin it'll be great to get a single summary per email (eg once a day or week - ideally customizable to your needs).

**Comment by Zodiac1978** [comment]
Please see https://github.com/wearerequired/digest/issues/8 for a possible future solution.

**Comment by thomastrethan** [comment]
Plugin Digest sounds good, looking forward to it.

**Comment by schlessera** [comment]
Third-party solution was apparently accepted. See #110 for a potential direct solution in a future version of ASB.
