### ISSUE TITLE
What does " Filter in the execution order" mean?

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#260]
![grafik](https://user-images.githubusercontent.com/6458412/50052961-5ad03600-0135-11e9-9bfb-89253cfa14a5.png)

Does anyone understand, what is meant by this phrase "Filter in the execution order". I think there is no real information in this phrase. Maybe we can consider to rephrase it.

**Comment by krafit** [comment]
This means the listed filters are executed in the mentioned order.
There is a tiny bit of information in this phrase but I agree: we don't need it :)

The question for me: should we change the string now or wait for ASB 3.0 to change the backend as a whole?

**Comment by 00travelgirl00** [comment]
lets wait to ASB 3.0 as it is not a blocker to use the Plugin.

**Comment by Zodiac1978** [comment]
As there is progress on 3.0 at the moment and we don't know how the backend will look in v3, I will close this for now, because it just clutters our issues without no real benefit.
