### ISSUE TITLE
Know your enemy

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#264]
![bildschirmfoto 2018-11-29 um 10 23 23](https://user-images.githubusercontent.com/870475/50540402-6d188e00-0b91-11e9-84c0-8d6cb1f06436.png)
![bildschirmfoto 2018-11-29 um 10 26 56](https://user-images.githubusercontent.com/870475/50540403-6db12480-0b91-11e9-8f72-36a397a046a7.png)

**Comment by websupporter** [comment]
Hi @Zodiac1978,

for context. Was this a spam comment you got?

**Comment by Zodiac1978** [comment]
Hi @websupporter ,
yes, I cleaned 13k spam comments from a website with an outdated ASB and found these two comments.
