### ISSUE TITLE
Problem with German language code 

### ISSUE THREAD

**Issue by wpaustria** [pluginkollektiv/antispam-bee#266]
Servus!
There are several problems with the language detection.
Concerning SPAM detection with franc.
This sentence is marked as spam:
"Super Fotos! Gefällt mir.
mfg"

![grafik](https://user-images.githubusercontent.com/33201121/51494138-e03fa980-1db7-11e9-9d3f-90f0e9f84d95.png)

franc (https://wooorm.com/franc/ ) detects this sentence perfectly as low german:
![grafik](https://user-images.githubusercontent.com/33201121/51494063-b4242880-1db7-11e9-81c4-e7f1121f3941.png)

So something went wrong within the plugin and the code I assume....

**Comment by wpaustria** [comment]
Thanks for your swift reply! Ok, I see where the problem's coming from. Will keep an eye on this.
Thanks for your efforts and keep up the good work!

**Comment by websupporter** [comment]
The problem is not the length of the comment but the code we get back from frac.

As the screenshot shows (and I also tested this with our API), we get `nds` for "Low German" instead of `deu` for "German".

**Comment by websupporter** [comment]
As a current workaround for @wpaustria 

```
add_filter(
'ab_get_allowed_translate_languages', function($languages) {
$languages['nds'] => 'Low German';
return $languages;
} );
```

You can register the code and then select it in the settings as well.

**Comment by websupporter** [comment]
Since we map the franc codes anyway to our iso codes, we could simply add 'nds' => 'de', to our array. 

reference:
https://github.com/pluginkollektiv/antispam-bee/blob/663c102b7a97bd09947d2f930b54ef231f93ccc7/antispam_bee.php#L1910

**Comment by websupporter** [comment]
Despite the `nds` mapping, it seems, we have a second problem with the string:
The string "Super Fotos. Gefällt mir. mfg" contains umlauts.
If I send (what I did in my first test) a plain string using Postman like
{ "body":"Super Fotos. Gefällt mir. mfg" } to our API, the API returns `nds`. But we use `wp_json_encode(['body' => 'Super Fotos. Gefällt mir. mfg'])` (basically `json_encode()`). Using `json_encode()` umlauts gets translated to:
`{"body":"Super Fotos! Gef\u00e4llt mir.mfg"}`.

If you send this string to our API, the API returns `src` (Logudorese Sardinian) which now is completely wrong. You can see it also here:
![grafik](https://user-images.githubusercontent.com/6458412/51590228-e5a10f00-1ef1-11e9-8f8e-1ef4b5d8f49f.png)

This indicates to me, our API does not handle json decode properly. @krafit

**Comment by KittMedia** [comment]
You’re right, that was a problem with the escaping. The API removed the `\` of the escaped unicode character. It should work now.
