### ISSUE TITLE
 Request for Autoptimize compatibility

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#278]
Check, if we can easily adjust our script to work smoothly with Autoptimize (https://wordpress.org/plugins/autoptimize/).

Autoptimize is a popular WordPress plugin, which caches inline scripts. Since our script differs with each post, the plugin has trouble with caching it.

We should see, if there is a way to optimize our script to work well together with this plugin. An path forward is described here: https://wordpress.org/support/topic/request-for-autoptimize-compatibility/

**Comment by Zodiac1978** [comment]
The solution looks fine to me.

**Comment by Zodiac1978** [comment]
Hi @websupporter - can you review this PR https://github.com/pluginkollektiv/antispam-bee/pull/282 
Thanks in advance!

**Comment by websupporter** [comment]
Thank you @Zodiac1978 
closed by #282
