### ISSUE TITLE
Compatibility issues with Epoch commenting system

### ISSUE THREAD

**Issue by schlessera** [pluginkollektiv/antispam-bee#28]
The WordPress plugin [Epoch](https://github.com/postmatic/epoch) does not work correctly in conjunction with Antispam Bee. When someone submits a new comment, it is not identified as spam, but Epoch retrieves the contents of the fake empty `textarea` instead of the hashed one (see [#185](https://github.com/postmatic/epoch/issues/185)).

An immediate solution would be to generate the same hash on Epoch's end to retrieve the contents from the correct `textarea`, but I suspect that the method of creating the `$secret` might change later down the road.

Is there a proper way to retrieve the `$secret` at the server end, to reliably integrate with other plugins?

**Comment by swissspidy** [comment]
Hey there,

Thanks for your report! We'll likely improve secret generation and retrieval in 2.7. Some effort has already been made in 55e5c422d74a8428a723883f7eee6a11abb54303 / #24, so this  will likely result in a public function/method that can be used by plugins like Epoch to reliably get AB's secret.

Sounds good?

**Comment by schlessera** [comment]
Yes, very nice. That would solve the issue on Antispam Bee's end and allow for a proper integration within Epoch.

Thanks for letting me know!

**Comment by schlessera** [comment]
The actual issue is solved in `master` by providing access to the secret IDs. I will follow up with Epoch to have this be included.
