### ISSUE TITLE
get_client_ip may fail if HTTP_FORWARDED doesn’t contain an IP address

### ISSUE THREAD

**Issue by KittMedia** [pluginkollektiv/antispam-bee#286]
Since the `HTTP_FORWARDED` doesn’t necessarily contains an IP address, the function `get_client_ip` may fail if there is just a `HTTP_FORWARDED` and the `REMOTE_ADDR` with the following values:

```
Array
(
    [REMOTE_ADDR] => 127.0.0.1
    [HTTP_FORWARDED] => proto=https
)
```

Since `HTTP_FORWARDED` is checked before `REMOTE_ADDR`, the further sanitation recognize that there is no IP address in it and thus fails. In this case, every comment gets marked as spam even if it isn’t.

I would recommend to change the sorting of the check so that `REMOTE_ADDR` gets checked before `HTTP_FORWARDED`, which may be available but without the IP address as is’t not necessarily available in the `HTTP_FORWARDED` variable.

**Comment by Zodiac1978** [comment]
This is about these lines: https://github.com/pluginkollektiv/antispam-bee/blob/e91ea009268516908d6d2242cb31be98aee1aa27/antispam_bee.php#L2352-L2366

Further reading:
https://stackoverflow.com/questions/1634782/what-is-the-most-accurate-way-to-retrieve-a-users-correct-ip-address-in-php
https://stackoverflow.com/questions/3003145/how-to-get-the-client-ip-address-in-php
https://security.stackexchange.com/questions/129662/best-approach-to-get-users-ip

After reading the SO topics I think we should follow the advice and put `$_SERVER['REMOTE_ADDR']` higher in the chain or we should save `$_SERVER['REMOTE_ADDR']` additonally beside the output from the rest.

Opinions @websupporter @schlessera ?

**Comment by KittMedia** [comment]
Thank you @Zodiac1978, this works well in our environment where the issue occurred. 👍🏻
