### ISSUE TITLE
New settings: Mark comments incl. urls/emails as spam

### ISSUE THREAD

**Issue by flowdee** [pluginkollektiv/antispam-bee#287]
It would be great to have two settings which allow me to automatically mark comments incl. email addresses and/or URLs as spam. This would help a lot

**Comment by Zodiac1978** [comment]
Unfortunately I can't follow. Can you please elaborate a little bit more about what you you are suggesting?

**Comment by flowdee** [comment]
Public comment was submitted and includes an email address or URL as text => Should be marked as spam (when setting activated)

**Comment by Zodiac1978** [comment]
I think this would produce too many false positives.

I would recommend using a custom pattern for this. You can find an example plugin here:
https://github.com/Zodiac1978/custom-patterns-asb
