### ISSUE TITLE
Reaktivierung der Option "Bestimmte Länder blockieren/zulassen"

### ISSUE THREAD

**Issue by sergejmueller** [pluginkollektiv/antispam-bee#29]
Guten Morgen ;)

Vielleicht könnt ihr euch an [den Tag](https://plus.google.com/+SergejMüller/posts/ZyquhoYjUyF) erinnern, wo ich zwei Plugin-Funktionen aus Kostengründen entfernen musste. Eine der beiden Funktionen war `Bestimmte Länder blockieren bzw. erlauben`.

Es hat sich auch rumgesprochen, dass ich https://ip2country.info gestartet habe: OpenSource-Projekte sollen es einfacher haben, IP-Adressen entsprechenden Ländern zuordnen zu können. Mit dem Dienst versuche ich mein Problem von damals zu lösen: Man habe ein OpenSource-Projekt und benötigt ein (kostenloses) GeoIP-Targeting.

Also: Theoretisch könnte man den Plugin-Filter  `Bestimmte Länder blockieren bzw. erlauben` wieder in Betrieb nehmen und mit ip2country.info verknüpfen. Man müsste nur den Code von damals wieder übernehmen (ist ja getaggt) und leicht anpassen (Request/Response). Mit anonymen IP-Adressen kann ip2country.info ebenfalls umgehen.

Was haltet ihr von der Idee und der Effektivität des Spam-Filters?

//cc @pixolin

**Comment by swissspidy** [comment]
Hey Sergej 👋

Wir haben schon ein paar Mal darüber gesprochen die Option wieder aufzunehmen. Es gab auch ab und zu User-Fragen diesbezüglich. Dafür hätten wir z.B. auch für die entstehenden Kosten zusammengelegt.

GeoIP-Targeting ist für viele Projekte sehr hilfreich, so auch bei der Spam-Bekämpfung, wobei man ja False Positives nie ausschliessen kann.

Dein Angebot mit ip2country.info ist sehr grosszügig und ich denke, das würden wir alle sehr gerne wieder in Antispam Bee sehen!

**Comment by swissspidy** [comment]
Bei #30 gibt es reihenweise Merge Konflikte.

Der PR sollte keine Übersetzungen beinhalten (läuft über WordPress.org) und auch nicht die Versionsnummern anpassen. Das sind unabhängige Tasks. Zudem sind einige Strings noch nicht übersetzbar.

Allerdings würde ich wirklich gerne zunächst Unit Tests haben, bevor wir gross an Features herumschreiben.

Zudem guter Input von @sergejmueller: Es braucht evtl. in den Einstellungen einen Hinweis, dass dabei Daten an einen externen Dienst gesendet werden. Das im Frontend anzuzeigen wäre meiner Meinung nach dann Sache des Site Owners.
