### ISSUE TITLE
Orphaned comment_meta: "antispam_bee_reason"

### ISSUE THREAD

**Issue by pfefferle** [pluginkollektiv/antispam-bee#293]
`_delete_old_spam` deletes only the comment without the comment meta.

**Comment by Zodiac1978** [comment]
Confirmed.

https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L963-L980

**Comment by websupporter** [comment]
solved in #295

**Comment by Zodiac1978** [comment]
Maybe we should clean up after us for all the `commentmeta` we already left (and for which the comment is already deleted).

WP Sweep is doing this with a `for each` and `delete_comment_meta` (orphaned commentmeta).

We could copy this code and ...

1: show a button to make this happen, 
2: doing it automatically (once) if there are orphaned commentmeta with `antispam_bee_reason`,
3: or just mention WP Sweep in changelog.

**Comment by krafit** [comment]
I'd prefere option 2 - cleaning up automatically - if we can somehow do it without too much overhead.

**Comment by websupporter** [comment]
I am torn between 2 and 3. But I tend to 3. It is about deleting data, which is _brrrr_. WP Sweep has a track record in doing its job. It has run through its bugs and should work as expected. This is a big plus.

Lets say, we do not introduce a bug (which might end bad), the question for me remains: How long do we need to keep this code in the codebase. When do we deprecate this "feature" or do we keep it indefinitely?

I see this situation is quite unfortunate. But currently I am not into writing a quite complex code (to me, option 2 requires a cron job to be "stable"). To refer in the changelog to a plugin, which does the job quite well looks to me as the best option between bad options.

**Comment by websupporter** [comment]
Any suggestions for where to put the documentation and phrasing?

**Comment by websupporter** [comment]
> 3: or just mention WP Sweep in changelog.
