### ISSUE TITLE
Add more RegEx patterns

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#298]
For example `luxurybrandsale`

**Comment by KittMedia** [comment]
What about these:
```
levitra
glucophage
hot girls
bank of
hookup
```

**Comment by Zodiac1978** [comment]
@KittMedia I am unsure about these, because I want to prevent false positives. 
Maybe we can better add phrases like "buy cialis" or "buy tramodol"?

**Comment by websupporter** [comment]
#299 added `luxurybrandsale`

**Comment by websupporter** [comment]
With the eyes towards a release of `2.9.2`: I would recommend to leave it for now with this one item and close this issue for now, it that's okay?

**Comment by Zodiac1978** [comment]
+1
