### ISSUE TITLE
Fake IP check is broken

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#304]
There is a check in our plugin called "Fake IP", but it is broken for IPv6, because the check compares the IP and the hostname which always returns `TRUE` - so every IPv6 comment is marked as spam.
https://github.com/pluginkollektiv/antispam-bee/blob/d7ad7fba3712ce99144bae56d08ce38807d6b5fa/antispam_bee.php#L1786

Maybe the IPv4 check is broken too, because a host can have more than one IP address and the host-to-ip/ip-to-host check does not necessarily match every time:
https://wordpress.org/support/topic/fake-ip-problem/

Should we remove the whole check? Can everyone please check if this check is working or if it only produces false positives? Thanks!

**Comment by Zodiac1978** [comment]
Related #19 and #27

**Comment by Zodiac1978** [comment]
This is the fix from the forums:

```
/**
	* Check for an IPv4 address
	*
	* @since   2.4
	* @change  2.6.2
	*
	* @param   string   $ip  IP to validate
	* @return  integer       TRUE if IPv4
	*/

	private static function _is_ipv4($ip)
	{
		//return preg_match('/^\d{1,3}(\.\d{1,3}){3,3}$/', $ip);
		return filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4) !== false ;
	}

	/**
	* Check for an IPv6 address
	*
	* @since   2.6.2
	* @change  2.6.2
	*
	* @param   string   $ip  IP to validate
	* @return  boolean       TRUE if IPv6
	*/

	private static function _is_ipv6($ip)
	{
		//return ! self::_is_ipv4($ip);
		return filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) !== false ;
	}
```

Needs to be tested and made into a PR.

**Comment by Zodiac1978** [comment]
I get error with this code:
`Warning: inet_pton(): Unrecognized address`
and
`Warning: dns_get_record(): An unexpected server failure occurred.`

Because PHP was compiled with --disable-ipv6 option.

Looks like this is not easy to solve ...

**Comment by websupporter** [comment]
Imo: Let's just get rid of it :)

**Comment by websupporter** [comment]
If no one is opposed to my suggestion to just get rid of the fake ip check, i will proceed in the coming days :)

**Comment by Zodiac1978** [comment]
I think we should get rid of this check, too. 

I always recommend to disable this option, because it creates problems with IPv6 (and we couldn't rely on PHP here, see comment above: https://github.com/pluginkollektiv/antispam-bee/issues/304#issuecomment-552579645) and with load balancing services.

At the hackathon we checked some databases for real spam caught with "Fake IP" and if I remember correctly, there are just false positives found ...

**Comment by Zodiac1978** [comment]
If this is too much work to remove, we could just leave it in and don't move it to 3.0.

**Comment by Zodiac1978** [comment]
@websupporter What do you think? Removing or don't move to v3?

I really would like to ship 2.9.2 with the light WP 5.4.
