### ISSUE TITLE
Kommentare nur in einer Sprache zulassen - Revival?

### ISSUE THREAD

**Issue by EdwardBlack** [pluginkollektiv/antispam-bee#31]
First of all, sorry for all the non-german readers of this topic. Because I will quote the author of this plugin, most of this post will be in german anyways so I thought I can ask in german aswell.

Hallo liebes pluginkollektiv-team,
erst einmal vielen Dank für eure Arbeit!

Sergej hat ja mit seiner Ankündigung vom Apr 10, 2015 die Funktion "Kommentare nur in einer Sprache zulassen" entfernt. Er schrieb dazu folgendes:

> Das Antispam-Plugin für WordPress verfügt über eine praktische Funktion, Kommentare nur in einer bestimmten Sprache zuzulassen - eingehende Kommentaren in anderen Sprachen werden automatisch als Spam eingestuft. Siehe dazu die Beschreibung im Handbuch: http://playground.ebiene.de/antispam-bee-wordpress-plugin/#translate_api
> 
> Um diese Option/Funktion ausführen zu können, wurde bis dato die inoffizielle Schnittstelle von Google Translation (Browser) API genutzt - die Schnittstelle war kostenlos und uneingeschränkt nutzbar. Bis vor wenigen Tagen.
> 
> Google hat die Nutzung dieser inoffziellen Schnittstelle nun insofern eingeschränkt, dass sie für automatische Skripte (was ein Plugin ja ist) nicht länger zur Verfügung steht. Um Google Translate API jetzt nutzen zu können, muss die kostenpflichtige Variante https://cloud.google.com/translate/v2/pricing implementiert werden. Früher oder später musste dieser Zeitpunkt ja kommen ;)
> 
> Da die Funktion im Plugin sehr effektiv ist, würde ich ungern sie aus dem Funktionsumfang rausnehmen. Andererseits möchte ich die Kosten für die API-Nutzung nicht selbst tragen (ich bezahle schon Maxmind, etc.) - allein die Ungewissheit beim Verbrauch machen mir Sorgen. Auch kann/will ich das Plugin nicht (teils) kostenpflichtig machen, weil das für mich einen enormen Aufwand bedeuten würde.
> 
> Zusammengefasst:
> Antispam Bee Nutzer mit aktiver Option „Kommentare nur in einer Sprache zulassen“ müssen damit rechnen, dass der Filter nicht einschlägt, da die Spracherkennung nicht mehr funktioniert.
> 
> Über eine Lösung grübele ich nach ;) Feedback willkommen ;)
> 
> Update 11. April 2015
> Um die Funktionsweise der genannten Funktion sicherzustellen, wurde soeben eine Version des Plugins mit der Nutzung der kostenpflichtigen Variante von Google Translation API online gestellt - bis auf Weiteres übernehme ich die Kosten (wie hoch auch immer diese ausfallen werden). Auch soll damit der API-Verbrauch ermittelt/gemessen werden. Nach einigen Wochen weiß man mehr, wie stark die Funktion und die dahinterstehende Translation-Schnittstelle genutzt wurden. Entsprechend sieht man die resultierenden Kosten.
> 
> Update 03. Mai 2015
> Eben eine Rechnung von Google bekommen: $55,22 bei 2.696.066 Einheiten im Zeitraum vom 11.04. - 30.04 (sind also nur 20 Tage). Da es davon auszugehen ist, dass das Plugin-Update nicht von allen Nutzern sofort aufgespielt wurde, müsste man mit mindestens ca. $90 pro Monat rechnen.
> 
> Update 16. Mai 2015
> Mit dem heutigen Plugin-Update wurden die beiden, für mich als Plugin-Autor kostenverbundenen Funktionen Kommentare nur in einer Sprache zulassen und Bestimmte Länder blockieren bzw. erlauben aus dem Funktionsumfang des Plugins entfernt. Schweres Herzens getan, auch wenn es mir nicht leicht fällt, den Antispam Bee Funktionsumfang um so starke Antispam-Filter zu reduzieren ;(

Quelle: https://plus.google.com/u/0/+SergejM%C3%BCller/posts/ZyquhoYjUyF

Jetzt meine Frage: Die Funktion um auf die kostenpflichtige API zuzugreifen scheint ja schon implementiert zu sein. Könntet ihr diese vielleicht wiederbeleben und als "Expertenfunktion" einpflegen so dass man in den Einstellungen ein Feld für den eigenen API-Key hat und diese somit aktivieren kann? (Selbe Frage gilt übrigens auch für Maxmind)

Nochmals danke an Sergej und euch für den klasse Job den das Plugin macht (Speziell zusammen mit Fail2Ban).

~Edward

**Comment by swissspidy** [comment]
Hey there,

Thanks for creating this issue. We're already tracking this in #29 and #30.

**Comment by 2ndkauboy** [comment]
Hallo Edward,

wir müssten uns mal ansehen, wie genau wir die Funktion einbinden könnten, damit sie ein Nutzer mit eigenem API-Key auf eigene Rechnung einrichten könnte. Ich denke eine solche Lösung sollte sich umsetzen lassen. Es muss dann nur auch gut kommuniziert werden, wie der Nutzer einen solchen API Key erhalten kann. Wenn du dies schon einmal gemacht hast, würde uns eine kurze Anleitung sicher weiterhelfen.

**Comment by swissspidy** [comment]
Oops, sorry. Mixed those two up.

**Comment by swissspidy** [comment]
Forcing users to set their own API key is not a great UX. We were thinking of sponsoring the API costs as a company before, but would need to look into it again.

**Comment by EdwardBlack** [comment]
You don't have to force the user, just give them the option if one thinks the function is usefull and one want to use it (that's the reason I mentioned to put it in a side menu - something like expert settings).

**Comment by swissspidy** [comment]
"Force" as in you have to get your own API key or it won't work. That's a bad UX.

Again, we were thinking of covering these costs, which would result in a much better UX.

If that doesn't work, I'd suggest putzing this in an add-on plugin.

No need to discuss implementation details before the basis is resolved though.

**Comment by sebastianbrinkmann76** [comment]
Just a short update: I get some russian and chinese spam during the last days and this feature would solve it. I just checked that version 2.7 wasn't published yet. Could you tell us, WHEN it will be published so that we can use this? I get let's say 10 spam comments per day and these guys aren't using your CSS Hack. :-)

**Comment by elbsurfer** [comment]
Hello,
there are a lot more spam comments coming through in the past days. I would really like to see this feature - together with #29 in the upcoming version. Especially the possibility to setup the plugin with the user's own API key to the necessary Google services is the right way to go.

**Comment by Zodiac1978** [comment]
@sebastianbrinkmann76 It is done, when it's done. There is no ETA at the moment.

@elbsurfer This is not very likely (see the discussion above). At the moment it looks like we will use the approach in #29

**Comment by sebastianbrinkmann76** [comment]
@Zodiac1978  Not my problem anymore, I start using WP SpamShield and it works well. It's really bad that development of this plugin slowed down so much.

**Comment by Zodiac1978** [comment]
@sebastianbrinkmann76 I tried to comment to your post about ASB, but your new Plugin hasn't allowed me to do so. Less spam is great. Block out real users is bad, I think. But hey, it is your decision which is the right plugin for you.

There is so much activity on this repo in the last time. Much more than ever before. But it is much more complicated to establish a workflow with a changing team of volunteers. Sergej was a genius one-man-show and it is not easy to fill his footsteps. We need to understand everything he has done in the past and elaborate on that, without any established honeypots/data/whatsoever. This needs time and data which has to be collected. The alternative was to let the plugin go, which would be even worse. Sadly you don't appreciate our unpaid work for the community. But again: it is your decision. Happy blogging.

**Comment by sebastianbrinkmann76** [comment]
@Zodiac1978 I really appreciate your unpaid work, but it's difficult to understand that this feature was build out in 2015 and two years after, there were only minor updates and you still cannot tell us, then this feature comes back. "It is done, when it's done" is not the friendly way to answer to a user question. I allready pay for WP Seo and Optimize, but I know that now it's not one man behind all of this anymore.

But, more important: can you tell me, then you tried to comment on my site? This would be the second report from a user that he was blocked and this would be to much, no question.  Can you send me an email to that I can check the logs?

**Comment by timse201** [comment]
If you really need this feature you can help us and test it. Just copy it to your server and tell us if anything goes wrong.

I can understand that spam can be anoying but this is the normal answer you will get when you use open source software.

**Comment by Zodiac1978** [comment]
> I allready pay for WP Seo and Optimize
Which is totally unrelated, because Pluginkollektiv has nothing to do with it and never has.

> can you tell me, then you tried to comment on my site?
It think you mean "when": According to my screenshot: 2017-01-17 11.07.35

> "It is done, when it's done" is not the friendly way to answer to a user question.
This is not meant offensive or unfriendly. I just don't know. I'm not capable to decide if every code is fine, so I need to wait for the other volunteers to review the code. If someone has the time, it could be tomorrow. If no one has the time it could be weeks from now. I just can't say. This is not a company. It is a open source project of volunteers. I have a blog myself with open comments and I feel the pain too ...
