### ISSUE TITLE
Rename blacklist/whitelist to a better phrase

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#311]
See: https://twitter.com/amlyhamm/status/1202684742069604353

In the thread there are several alternatives:
"safelist" and "blocklist"
"allowed/denied" - allow/deny
“Trusted” and “blocked”
"pass" and "block"
"Picklist" and "banlist"
“red-list” and “green-list” (Hmm.)
permitted/prohibited or allowed/blocked.

https://github.com/pluginkollektiv/antispam-bee/blob/9e4f08e24f0776ffab5d4b3a030af87a3f48b027/inc/gui.class.php#L311
and
https://github.com/pluginkollektiv/antispam-bee/blob/9e4f08e24f0776ffab5d4b3a030af87a3f48b027/inc/gui.class.php#L326

I would recommend this:
`Allowed  %1$sISO Codes%2$s for this option.`
and
`Denied  %1$sISO Codes%2$s for this option.`

**Comment by krafit** [comment]
I'm a bit late to the party, but I'm very much in love with Torstens idea.

I'd just add one tiny little detail. A non technical person will probably not be aware of ISO Codes. Lets call them `ISO country Code` or something like that, to make it more obvious (I'm aware of the link, but it would not hurt to make it easier to understand).

**Comment by Zodiac1978** [comment]
Although this is a small change we should mention this in the changelog, to make our translators aware of this issue. (And change the German translation as it is using Blacklist/Whitelist additionally.

**Comment by websupporter** [comment]
Reopen issue to not loose track of @Zodiac1978 last comment before we release.

**Comment by websupporter** [comment]
Should be solved in #326
