### ISSUE TITLE
PHP 7.4 compatibility

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#315]
Do we need to do something for PHP 7.4? 

It looks like Travis is not checking against 7.3 or 7.4 - correct?
@websupporter 

First asked here:
https://wordpress.org/support/topic/php-7-4-3/

https://www.php.net/manual/de/migration74.php

**Comment by Zodiac1978** [comment]
WP Tide in Site Health Check plugin is reporting 7.3 for Antispam Bee. :/

**Comment by websupporter** [comment]
I updated the test suite. During plugin activation we do currently run into a problem. #316 fixes this.
