### ISSUE TITLE
Caldera Forms supported?

### ISSUE THREAD

**Issue by strarsis** [pluginkollektiv/antispam-bee#318]
According to the Caldera Forms [docs about adding anti spam protection](https://calderaforms.com/doc/protect-form-spam-caldera-forms/) to Caldera Forms,
this Antispam Bee plugin can also protect Caldera Forms against spam.

I installed + enabled the Antispam Bee plugin.
How can I find out whether it is protecting the Caldera Forms?
Does Antispam Bee filter the `$_POST` data automatically, 
so Caldera Forms plugin doesn't need any special hooks/processors to integrate Antispam Bee?

Is it possible to trigger spam detection by entering and submitting some text in the form that 
is 100% detected (and hopefully blocked/dropped) as spam?

**Comment by websupporter** [comment]
Hi @strarsis,
unfortunatly Antispam Bee does not work for Caldera forms. We reached out to the developers of Caldera forms to ask them to remove us from the list. Seems, this request was forgotten in the meantime.
https://twitter.com/websupporter/status/1062279919391162368

@Shelob9 fyi

**Comment by strarsis** [comment]
@websupporter: Hm, how hard would it be to integrate Antispam Spee into Caldera Forms?
If I understand the concept correctly, Antispam Bee takes in some data, like the message body, email, client IP address parts, and then decides whether the user is legit or a spammer.
Caldera Forms can either just internally drop the submitted message or sort/mark it separately for later view, and if it sends an email of the submitted form it can flag it so the email server/client can sort it into a folder for possible junk mail.

**Comment by websupporter** [comment]
Hi @strarsis,
altogether it wouldn't be too hard to realize it, I guess. We are currently working on Antispam Bee 3.0 (#314) , which would give us a more modular expressed code base exactly for those purposes. After we have finished 3.0 (currently there is no real timeline, as it is quite a time consuming process and we want to do it right), we should consider such an enhancement in one way or the other.

**Comment by Zodiac1978** [comment]
The docs are corrected now, so I will close this issue.

The progress of v3 and the Support of contact forms is handled in another issue.
