### ISSUE TITLE
Public blacklists

### ISSUE THREAD

**Issue by strarsis** [pluginkollektiv/antispam-bee#319]
Cleantalk uses a public IP blacklist and I was able to match all the form spammer IPs.
Also I noticed that DNS Blackholes that are used by mail servers often also contain these form spammer IPs.
Could Antispam Bee use these blacklists?

**Comment by Zodiac1978** [comment]
This is a privacy problem. Public IP blocklists use non-anonymized (aka full) IP addresses which violates GDPR if we share IP addresses with them.

**Comment by strarsis** [comment]
@Zodiac1978: Would a lookup with truncated IP addresses go around the privacy issue?

**Comment by Zodiac1978** [comment]
@strarsis Yes, I think so, but I don't know any blocklist with truncated IPs. Comparison of IP hashes could be another way. But the problem remains: I don't know any reliable blocklist which is just comparing hashes. Can you share a blocklist which would be compliant with the GDPR?

**Comment by krafit** [comment]
Since we explicitly removed public database lookups to make sure Antispam Bee is GDPR compliant, I don't see a path forward including this feature in ASB core.
Once version 3.0 (#314) is released, there might be a use case for an add-on.

Let's close this issue for now.
