### ISSUE TITLE
Wiki: 'Filterdatei' missing

### ISSUE THREAD

**Issue by EdwardBlack** [pluginkollektiv/antispam-bee#32]
The 'Filterdatei' mentioned in the documentation is missing respectively the link is broken.

> **Logdatei für Fail2Ban**
> 
> Das Antispam-Plugin ist in der Lage, erkannten Spam in einer Logdatei zu protokollieren. Das kann sehr nützlich sein, um Spam-Anfragen mithilfe von Fail2Ban bereits auf der Server-Ebene zu erkennen und abzuwehren. Für diesen Zweck wurde eine Filterdatei für die Fail2Ban-Konfiguration entwickelt. Simple Inbetriebnahme der Funktion: In der WordPress-Konfigurationsdatei wp-config.php das Logging für Antispam Bee aktivieren, indem der Konstante ANTISPAM_BEE_LOG_FILE der Server-Pfad zum Logfile zugewiesen wird. Die Datei muss beschreibbar sein. Exemplarisch: define('ANTISPAM_BEE_LOG_FILE', '/var/log/spam.log'); Implementierung: Antispam Bee 2.5.7

**Comment by swissspidy** [comment]
Thanks for your report. Guess we need to remove that link.

**Comment by EdwardBlack** [comment]
The usage of fail2ban is one of the greatest features of antispam-bee for any larger website. Would be great if you can find the missing file or get it from Sergej.

**Comment by Zodiac1978** [comment]
Here are two posts about the feature showing examples of this configuration:
https://tamcore.eu/spammer-mit-fail2ban-und-antispam-bee-loswerden/
http://wemaflo.net/2013/05/23/wordpress-gegen-spam-schutzen-mit-fail2ban-und-antispam-bee-fur-ispconfig-server/

**Comment by sdellenb** [comment]
I guess that would be the updated link:
https://gist.github.com/sergejmueller/8562240

**Comment by sdellenb** [comment]
I'm using a configuration like this now:
/etc/fail2ban/filter.d/wordpress-antispam-bee.conf
```
# Fail2Ban configuration file for Antispam Bee.
[INCLUDES]
before = common.conf
[Definition]
failregex = comment for post=\d+ from host=<HOST> marked as spam$
ignoreregex =
```

/etc/fail2ban/jail.d/99-wordpress-antispam-bee.conf
```
[wordpress-antispam-bee]
enabled  = true
filter   = wordpress-antispam-bee
logpath  = /var/log/spam.log
# Since there are only a handful of registered users, we can use very aggressive settings.
maxretry = 2      ; Fail 2 times
findtime = 86400  ; within a day
bantime  = 172800 ; and you're out for two days.
```

**Comment by Zodiac1978** [comment]
> I guess that would be the updated link:
> https://gist.github.com/sergejmueller/8562240

No, it isn't. Antispam Bee is using 403 and not 401 to mark/block the spam.
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error

**Comment by sergejmueller** [comment]
https://tamcore.eu/spammer-mit-fail2ban-und-antispam-bee-loswerden/

**Comment by Zodiac1978** [comment]
@sergejmueller https://github.com/pluginkollektiv/antispam-bee/issues/32#issuecomment-219671258 :)
