### ISSUE TITLE
Add user agent to regex check

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#322]
This feature request is coming from the support forums:
https://wordpress.org/support/topic/feature-request-block-comments-depending-on-user-agent/

The information is in the database. The `wp_comments` table has a field `comment_agent` which contains the user agent of the comment author:
https://codex.wordpress.org/Database_Description#Table:_wp_comments

We could add this to this block:
https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L1354-L1358

`$useragent      = self::get_key( $comment, 'comment_agent' );`

and to this block:
https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L1408-L1415

`'useragent'     => $useragent,`

and to this block:
https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L1526-L1530

`'useragent',`

This should be easy to add and would open up the user agent info to the regex pattern feature.

**Comment by Zodiac1978** [comment]
After digging a little bit more in the code from WordPress itself, I found a hidden feature (aka bug). The moderation/block list on the discussion settings page can be used with user agent strings too.

Will be fixed/documented with WP 5.5.

See: https://core.trac.wordpress.org/ticket/49902

**Comment by websupporter** [comment]
Will close this issue since 49902 provides already a possibility and #322 was closed in favour of 49902 as well. Thanks for digging into it :)

**Comment by Zodiac1978** [comment]
After the ticket is fixing the underlying issue that was preventing this, I re-open this issue for reconsideration.
Related: https://core.trac.wordpress.org/ticket/51044
