### ISSUE TITLE
Road to 2.9.0

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/antispam-bee#33]
I moved a bunch of issues to the 2.7.0 milestone today to give us a little bit of a challenge.

I also updated master to include changes for 2.6.9. That release basically only needs to be committed to the plugin directory.

2.7.0 includes mainly bug fixes, but also some suggested features (not set in stone!). Before we implement any of these, I really want to have a solid structure so we can add proper unit tests along the way. See pluginkollektiv/antivirus#13

We should also think about a proper workflow to do stuff like:
- ~Minify CSS and JS upon build.  
  The GitHub repository shouldn't include minified assets.~
- ~Add PHP_CodeSniffer rules.
  To ensure we follow the WP coding standards.~
- Add other tools to catch mistakes like missing text domains.
- ~Use a proper deploy script.
  Committing to SVN by hand is annoying. https://github.com/stephenharris/grunt-wp-deploy/ is the de-facto standard IMHO and a new version of that script is coming out soon.~

**Comment by timse201** [comment]
you can add the project to https://travis-ci.org/ which could help testing

**Comment by swissspidy** [comment]
Travis is implicitly included in that list for all our plugins 🙂

**Comment by timse201** [comment]
ok xD
didnt read that

**Comment by websupporter** [comment]
Coding standards and travis ci for these standards have been introduced with #188
