### ISSUE TITLE
Report spam in ASB itself

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#330]
In this issue we can discuss ideas and problems of providing a feature to report spam from within ASB.

We could the transformation action hooks `comment_unapproved_to_spam and` `comment_approved_to_spam` or we could provide a button / action link for this.

Possible problems: Privacy concerns (IP, Mail, Content, etc. from Comments) are submitted to us (or a Third-Party-Service like Google Forms).

This needs feature needs consent from the user:
https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#7-plugins-may-not-track-users-without-their-consent

**Comment by krafit** [comment]
I'd suggest to discuss this in #73 :)

**Comment by Zodiac1978** [comment]
Ah, there is already one :)
