### ISSUE TITLE
JS Option like "Anti Spam"

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/antispam-bee#339]
_Originally posted by @PopVeKind in https://github.com/pluginkollektiv/antispam-bee/issues/289#issuecomment-619920196, I moved this suggestion to its own issue._

_Just throwing this out there..._

I used the "Anti Spam" Plugin for a lot of years on hundreds of sites. I loved it. It **_was_** a lightweight JS Anti Spam. I still am using Anti Spam Ver 5.5 to protect over 100 sites.

_(Short Rant, skip to next paragraph.)_ Sadly the project was sold, and as "[Titan](https://wordpress.org/plugins/anti-spam/)  Anti-spam" it is bloated, slow, uses 3rd party websites, and has advertizer bloat also. These people are tricking people, without warning, into "upgrading". Worst of all, the NEW plugin does NOT stop spam nearly as well as the old JS plugin did! _(End of Rant!)_

However, the old code, Anti Spam 5.5 can be view/downloaded from my Github [https://github.com/PopVeKind/anti-spam](https://github.com/PopVeKind/anti-spam) It may be useful to compare while building a JS option. _For what its worth._

Obviously, **I am in favor of a lightweight JS Option.** If this option is enabled, and if JS is enabled on the client, I would do this test first. If JS is not enabled on the client, go straight into the other options.

So much for my idea! _Thanks for listening._

**Comment by Zodiac1978** [comment]
This issue comes from the support forums. Reference for completeness:
https://wordpress.org/support/topic/new-faq-how-to-configuare-antispam-bee-like-anti-spam/

**Comment by krafit** [comment]
Hey @PopVeKind,

welcome and thank you for bringing this up. I understand, a plugin being discontinued or heading the wrong direction isn't a pleasant experience at all.

To be frank, I never saw the benefit in implementing (parts of) Antispam Bee as JS on the client side. That's mainly because the PHP parts of ASB work pretty fine. And with our big version 3.0 coming up, we'll have enough to do already.

However, since you are the expert on JS-based solutions, I'd love to hear from you, what the benefits of doing spam detection on the client side are, and what Anti-Spam did _right_ in your opinion. Maybe there is a thing or two, we could learn from their way of doing things.

Cheers,
Simon

**Comment by krafit** [comment]
Since this issue didn't really gain any attention, I'd opt to close it for now.
