### ISSUE TITLE
franc is detecting wrong language if comment body contains links

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#341]
False positive for 
`Hi
Danke für den Tip.Ich nutze bisher immer:
https://www.whatsmydns.net/
Liebe Grüsse
Reinhard`

[franc](https://wooorm.com/franc/) is detecting Danish.

Without the link it is detecting `nds` which is mapped to `de` and therefore works.

This is the second false positive I see after the obvious Russian comment which was detected as Kinyarwanda.
Without the link it was correctly detected as Russian.

**Comment by Zodiac1978** [comment]
@krafit I still don't know if this is fixed on the API side or not. Have you tested it but not made it live or what is the status here?

**Comment by krafit** [comment]
@Zodiac1978 yep, we tested it, but it's not live yet.

**Comment by KittMedia** [comment]
I’ve took the code live:
```
$post_array['body'] = preg_replace( '/\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|$!:,.;]*[A-Z0-9+&@#\/%=~_|$]/i', '', $post_array['body'] );
```

**Comment by florianbrinkmann** [comment]
Made a request with the text »Hi Danke für den Tip.Ich nutze bisher immer: https://www.whatsmydns.net/ Liebe Grüsse Reinhard« and got `nds` correctly.
