### ISSUE TITLE
preprocess_comment filter not having all data

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#350]
We are using the `preprocess_comment` filter to handle the incoming requests:
https://github.com/pluginkollektiv/antispam-bee/blob/e1b9366c6ce7e0d3dcdb127e74a841914795ff30/antispam_bee.php#L314

But not all information is there at this time. Some information, like the user agent, is added after the filter.

I've opened a trac ticket for this: https://core.trac.wordpress.org/ticket/51044

But we should also think about possible problems within ASB because of this.

**Comment by florianbrinkmann** [comment]
Can this ticket be closed @Zodiac1978?

**Comment by Zodiac1978** [comment]
Yes, I think so.
