### ISSUE TITLE
Test system needs update

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#356]
WordPress version 5.4 is missing, because after WordPress 5.5 was released we just test 5.3 and then latest version and nightly version.

It seems that the old behat test is used if the branch was made before the change. At least this is the only idea I have, why the build is failing for build #739 (https://travis-ci.org/github/pluginkollektiv/antispam-bee/builds/731926635)

The PR is from today, but the branch was made for weeks/months ...

Hopefully this can be fixed, so that behat is using the corrected version.

**Comment by jonathanbossenger** [comment]
@Zodiac1978 thanks for tagging me on this one.

**Comment by jonathanbossenger** [comment]
@Zodiac1978 thanks for assigning me.

Just so you know, my goal is to work on this during the 2nd week of October, so you won't see any activity from me this week.

**Comment by jonathanbossenger** [comment]
@Zodiac1978 sorry this took so long to get to, work got in the way.

I've created a fork for this in my profile, so that I can trigger builds without affecting yours.

You can follow along here: https://github.com/jonathanbossenger/antispam-bee

And here: https://travis-ci.org/github/jonathanbossenger/antispam-bee

**Comment by jonathanbossenger** [comment]
@Zodiac1978 quick update here. It looks like one of the possible reasons for the failure is that Travis is using composer 2 and some of the composer packages are incompatible. 

https://travis-ci.org/github/jonathanbossenger/antispam-bee/jobs/740254586

I still need to update my own workstation with composer 2, so I will work on that next week and hopefully get some results.

BTW no need to worry about hacktoberfest here, I've managed to create my 4 qualifying PR's elsewhere, but this is an interesting little problem to solve, so I'll keep at it.

**Comment by jonathanbossenger** [comment]
@Zodiac1978 PR created. If you want to see the specific tests I mentioned that are failing, you can do so here https://travis-ci.org/github/jonathanbossenger/antispam-bee
