### ISSUE TITLE
Add contributors to WordPress readme.txt

### ISSUE THREAD

**Issue by pfefferle** [pluginkollektiv/antispam-bee#360]
@Zodiac1978 had the idea, to add the contributors to the readme.txt to give credit for their work and to motivate to further contribute.

We started an Antispam Bee weekly in the rocket chat and I would suggest, to discuss new contributors there, to keep the "process" simple.

What do you think about the idea and who should we add?

I would suggest to use the GitHub Contributors list as a start: https://github.com/pluginkollektiv/antispam-bee/graphs/contributors Maybe add the first 6 to 10 contributors?

**Comment by florianbrinkmann** [comment]
Sounds good!

**Comment by pfefferle** [comment]
I started a MR with the first 8. Any thoughts about the number? Extend to 10? Add all?

**Comment by florianbrinkmann** [comment]
8 sounds good as a starting point, but I guess we should ask all of them if they want to be added there

**Comment by Zodiac1978** [comment]
Caspar has retired his glueckpress brand: https://gist.github.com/glueckpress/433123705b9be0cc41748937de020b44
Not sure about if it is possible to change a wordpress.org account ...

**Comment by krafit** [comment]
> Not sure about if it is possible to change a wordpress.org account ...
Changing a w.org user name is not possible right now.

I‘d also like to add, that i like the idea of adding the contributors. But the list @pfefferle might not be the best point to start with. On the one hand it seems to be not that complete - I myself for example had at least a dozen commits to ASB and none(!) are listed there. While at the same time a user like timse201, who’s commit style was spammy at best, ranks second on the list, with (in respect to the 2nd position) little to show for.

**Comment by pfefferle** [comment]
@krafit what about, you (the plugincollekiv crew that is listed on the site) are nomination people to start? I just thought I start with a MR.

**Comment by pfefferle** [comment]
I deleted the MR for now, because I think there should really be a nomination/discussion first.

**Comment by Zodiac1978** [comment]
Then I would like to nominate @websupporter @schlessera @swissspidy @krafit after looking at the merged PRs as a start.

**Comment by swissspidy** [comment]
Definitely need to include you in that list too, @Zodiac1978!

**Comment by pfefferle** [comment]
any other nominees?

**Comment by Zodiac1978** [comment]
Of course there is @2ndkauboy missing. Sorry I forgot you in the first round ;)

**Comment by Zodiac1978** [comment]
Todo: Adding @pfefferle :)
