### ISSUE TITLE
Update screenhot(s)

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#368]
There was a new screenshot added in #204 but we do not added it on SVN. :(

The assets folder is a top level directory on SVN (1) , so we may need to find a way adopt these changes in our new Github actions workflow from @2ndkauboy 

Because we had no server at first, we used an own Github repo (2) to organize our assets. 

We should update those screenshots/assets and find a way to make this more easy to integrate with our actions workflow.

Maybe just add here: https://github.com/pluginkollektiv/antispam-bee/tree/master/.wordpress-org
and change the readme.txt

[1] https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/

[2] https://github.com/pluginkollektiv/assets - for Antispam Bee: https://github.com/pluginkollektiv/assets/tree/master/antispam-bee/images

**Comment by krafit** [comment]
Yes, `.wordpress-org` is the directory to host this kind of files. We already use it over at the [Cachify repo](https://github.com/pluginkollektiv/cachify/tree/develop/.wordpress-org).

**Comment by Zodiac1978** [comment]
I don't think these huge images are a good idea. The image slider on wordpress.org is 609 pixel wide and therefore nothing is readable on this screenshot.

I would prefer the approach from before with screenshots of each area:
https://github.com/pluginkollektiv/assets/tree/master/antispam-bee/images

This would be readable in the slider.
