### ISSUE TITLE
PHP Notices

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#372]
I checked for issue on WordPress 5.6 and found some PHP Notices with ASB (on /wp-admin/edit-comments.php):

map_meta_cap was called incorrectly. The post type scheduled-action is not registered, so it may not be reliable to check the capability "edit_post" against a post of that type. Please see Debugging in WordPress for more information. (This message was added in version 4.4.0.)

and

Trying to get property 'labels' of non-object

and

Trying to get property 'view_item' of non-object

The stack trace is not helpful and just shows WP internal files.

**Comment by Zodiac1978** [comment]
This is event true for WordPress 5.6 without any of our plugins activated. Can someone confirm this?

**Comment by 2ndkauboy** [comment]
I can't confirm. Tested on `5.6-RC1-49694` and `PHP 8.0.0` on my test domain both with latest stable and `master`.

**Comment by florianbrinkmann** [comment]
I cannot reproduce that, too.

**Comment by Zodiac1978** [comment]
Great! Then it is something in my test environment. Thanks for your feedback.
