### ISSUE TITLE
Add check If GMail address exists

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#373]
https://gist.github.com/m1guelpf/76ae12374689691485f00c1e6126fca0

Found on Twitter: https://twitter.com/m1guelpf/status/1333127992260882436?s=21

**Comment by Zodiac1978** [comment]
A first test shows that this would actually help us to get some of the undetected spam comments from our reported spam list.

But we need to remove "+" and everything after it, because this breaks the test result, but the mail is valid.
See: https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html

**Comment by Zodiac1978** [comment]
I know you have some experience with APIs @2ndkauboy - would you be interested in working on this (after checking the privacy part)?

**Comment by Zodiac1978** [comment]
Maybe @swissspidy or @felixarntz can help us to verify if this API endpoint is okay to use for us? Or can link us to the right people?

**Comment by swissspidy** [comment]
I think the tweet itself already says that it's a hidden/undocumented API :) Personally I wouldn't rely on such undocumented APIs for production code, as you never know when it might change or disappear. Also, I'd assume there is some rate limiting that prevents you from making more than X requests to that API per day or so.

----

> But we need to remove "+" and everything after it, because this breaks the test result, but the mail is valid.

FWIW there's apparently a package for that: https://github.com/imliam/php-unique-gmail-address

**Comment by Zodiac1978** [comment]
Yes, we know, that's the reason I pinged you. It would be beneficial to use this, but the limitations and risks are high. Any chance to get this as a reliable endpoint?

**Comment by PraetorIM** [comment]
There is another problem: The transmission of the mail to Google isn't covered by a legitimate interest (under data protection law); because what should be the interest to check Gmail addresses, but accept other addresses?
