### ISSUE TITLE
Test with WP 5.7

### ISSUE THREAD

**Issue by florianbrinkmann** [pluginkollektiv/antispam-bee#377]
WordPress 5.7 is scheduled for March 9, so we need to:

- [x] test with the current WP 5.7 RC
- [x] add Tested up to: 5.7 to the plugins readme
- [x] publish changes as minor update or with upcoming plugin update

**Comment by florianbrinkmann** [comment]
I manually ran most of the behat tests (manually, because there are issues with the chrome webdriver in GitHub action, I need to work on that -.-) with WP 5.7 RC2 and everything worked as expected. The SSL cert for the API server was expired so the language checks were not working, but @MatzeKitt fixed that.

**Comment by Zodiac1978** [comment]
Didn't found any problems in RC2 so far.

Tested up to is changed to 5.7, but action seems to have failed.

Maybe @2ndkauboy can help to get this sorted out on SVN.
