### ISSUE TITLE
404s for missing gists, dead links in wiki

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#38]
## 404 for missing gists in code

https://github.com/pluginkollektiv/antispam-bee/blob/9a8e8e74a98804e858ad470376c4e5c4a74842ac/inc/gui.class.php#L214
https://gist.github.com/4242142

https://github.com/pluginkollektiv/antispam-bee/blob/91e09655f7aa882984fdc6d5a1d3791a132bcecf/README.md
EN: Optional logfile with spam entries e.g. for Fail2Ban
https://gist.github.com/sergejmueller/5622883
## 404 for missing gist in documentation/wiki

https://github.com/pluginkollektiv/antispam-bee/wiki/Dokumentation
Dafür wurde eine Schnittstelle geschaffen, die weitere RegExp-Regeln annimmt und verarbeitet. Beispiel auf GitHub zeigt die Methodik der Filter-Erweiterung. Sieht simpel aus, doch die Option ist sehr mächtig und vielfältig:
https://gist.github.com/4242142

## missing posts/anchor after redirect in changelog/wiki

~~https://github.com/pluginkollektiv/antispam-bee/wiki/Versionsverlauf~~

~~Jubiläumsausgabe Neues Antispam Bee Maskottchen Antispam-Prüfung ankommender Kommentarbeiträge auf URL, IP- und E-Mail-Adresse in lokaler Blog-Spamdatenbank Version~~
http://playground.ebiene.de/antispam-bee-wordpress-plugin/#spam_ip

~~Neue Funktion: Reguläre Ausdrücke anwenden Weitere Verknüpfungen der Sprachdatei im Plugin Veränderte Reihenfolge der Erkennungsfilter~~
http://playground.ebiene.de/antispam-bee-wordpress-plugin/#regexp_check

~~Interaktive Dashboard Spam-Statistik (analog zu Statify) Farbliche Anpassung der Optionsseite an WordPress 3.2~~
http://playground.ebiene.de/statify-wordpress-statistik/

~~Verzicht auf die von Google eingestellte Translate API (Die Core-Funktion bleibt aber erhalten)~~
http://playground.ebiene.de/antispam-bee-wordpress-plugin/#translate_api

~~Berücksichtigung des bereits erkannten Spam Kommentare nur in bestimmter Sprache zulassen Verzicht auf Canvas im Statistik Widget Gruppierung der Bereiche innerhalb der GUI Umstellung der Mindestvoraussetzung auf WordPress 2.8 Erhöhung der Sicherheit innerhalb des Plugins Entfernung des Migrationsskriptes Spam-Grund nun auch in der Spam-Übersicht Interne Strukturveränderungen~~
http://playground.ebiene.de/antispam-bee-wordpress-plugin/#spam_ip
http://playground.ebiene.de/antispam-bee-wordpress-plugin/#translate_api

~~Spamaufkommen als zuschaltbare Verlauf-Statistik auf dem Dashboard~~
http://playground.ebiene.de/antispam-bee-wordpress-plugin/#dashboard_chart

~~Visuelle Überarbeitung der Benachrichtigungsemail Angabe des Verdachtsgrunds in der Benachrichtigungsemail Länderspezifische Blockierung von Kommentaren (Optional) Abgleich mit der Spammer-Datenbank von Project Honey Pot (Optional) Modernisierung der GUI + Ausklappbare Optionen~~
http://playground.ebiene.de/antispam-bee-wordpress-plugin/#email_notify
http://playground.ebiene.de/antispam-bee-wordpress-plugin/#country_code
http://playground.ebiene.de/antispam-bee-wordpress-plugin/#honey_pot

**Comment by Zodiac1978** [comment]
Wayback Machine just gives us the first 10 lines ... :(
https://web.archive.org/web/20130116205022/https://gist.github.com/4242142
Benutzerdefinierte WordPress-Filter für das Antispam Bee Plugin. Spam-Markierung anhand von Regulären Ausdrücken.

`<?php

/*
Antispam Bee filter for custom RegExp patterns
Customize and paste it into functions.php
*/
 
add_action(
	'init',
	'antispam_bee_patterns'`

**Comment by timse201** [comment]
some related links that could help:
patterns:
http://www.online-erfolgreich.net/webseite-und-technik/spam-bekaempfen-mit-antispam-bee-und-regulaere-ausdruecke-via-plugin-hook/
http://torstenlandsiedel.de/2017/01/08/custom-pattern-fuer-antispam-bee/

fail2ban:
think we can change these links to
german:
https://wiki.ubuntuusers.de/fail2ban/
(not dead yes but think there are more infos

english:
https://help.ubuntu.com/community/Fail2ban
