### ISSUE TITLE
ip2country API

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#388]
There is a notice (maybe for longer, I just saw it now) on http://ip2country.info/

> Exciting News!
>
> IP2country is joining ipapi.com to offer an even more advanced IP API, now offering IP address geolocation & reverse IP lookups in real-time at an unparalleled level of accuracy. To keep using our API, switch to ipapi.com and get your free API key. 

Does anyone have more information about this? Looks like we need to remove this or find a way to use the API key without making it public.

**Comment by Zodiac1978** [comment]
Ping @sergejmueller @schlessera 

When will the service stop? Does anyone have more information about this or has found this info on the page?

Additional problems: 
* Free plan is limited to 10k (not enough for 600k active installations - even if not alle are using it)
* No https in free plan

**Comment by Zodiac1978** [comment]
I have DMed Sergej and he has no further information about it. This means: The service can stop every moment.

I will try to contact them, but I think there is no chance to keep the check in this way.

Some plugins offer a way to download Geodata files and use them in WordPress itself to check this. This could be one new way to implement this feature in the future. Bundling the files seems to be against the license.

Or we use the same way like with the Safebrowsing API in Antivirus. The user can get a plan and just needs to set up an API key in the settings.

Both ways are not ideal: What is your opinion?

**Comment by 2ndkauboy** [comment]
https://iplocate.docs.apiary.io/#introduction/code-samples
