### ISSUE TITLE
Move changelog

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/antispam-bee#39]
We should move the majority of the changelog into a separate `CHANGELOG.md` file and and only keep the most recent entries. Plus, we can link to that file from the Wiki page.

Translating a long changelog is a huge pain for translators and not very useful. Plus, the plugin directory doesn't like readme files that are too long.

Already did this successfully for [Statify](https://github.com/pluginkollektiv/statify).

**Comment by timse201** [comment]
can be closed
