### ISSUE TITLE
Optimize FAQ entry about AJAX comment plugins

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#390]
In our FAQ we write:
> It also won’t work with any AJAX-powered comment forms.

After the merge of #355 we should tackle #376 and also we should update the FAQ to reflect this change.

**Comment by Zodiac1978** [comment]
We could link to my post, but it is just available in German:
https://torstenlandsiedel.de/2020/10/04/ajaxifizierte-kommentare-und-antispam-bee/

**Comment by Zodiac1978** [comment]
https://github.com/pluginkollektiv/antispam-bee/blob/master/readme.txt#L67

**Comment by florianbrinkmann** [comment]
- [ ] Add own FAQ entry about the AJAX topic

**Comment by Zodiac1978** [comment]
Status Quo:
### Does Antispam Bee work with Jetpack, Disqus Comments and other comment plugins? ###
Antispam Bee works best with default WordPress comments. It is not compatible with Jetpack or Disqus Comments as those plugins load the comment form within an iframe. Thus Antispam Bee can not access the comment form directly.
It also won’t work with any AJAX-powered comment forms.

Suggestion:
### Does Antispam Bee work with Jetpack, wpDiscuz, Disqus Comments and similar comment plugins?

Antispam Bee works best with default WordPress comments. It is not compatible with Jetpack, wpDiscuz or Disqus Comments as those plugins load a new comment form within an iframe. Thus Antispam Bee can not access the comment form directly.

### Does Antispam Bee work with AJAX comment plugins or similar theme features?

Whether Antispam Bee works with a comment form submitted via AJAX depends on how the AJAX request is made. If the request goes to the file that usually also receives the comments, Antispam Bee could work with it out of the box (the [WP Ajaxify Comments](https://wordpress.org/plugins/wp-ajaxify-comments/) plugin does this, for example). 

If the comments are sent to the admin-ajax.php, the antispam_bee_disallow_ajax_calls filter must be used to run ASB for requests to that file as well. If the script does not send all form data to the file, but only some selected ones, further customization is probably necessary, as [exemplified in this post by Torsten Landsiedel](https://torstenlandsiedel.de/2020/10/04/ajaxifizierte-kommentare-und-antispam-bee/) (in German).

**Comment by florianbrinkmann** [comment]
Looks good!
