### ISSUE TITLE
Plugin incompatibility Ezoic Integration

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#391]
After installation and activation of this plugin our Honeypot is gone:
https://wordpress.org/plugins/ezoic-integration/

Not sure why this happens and if there is something we can or should do to prevent this.

First reported here: https://wordpress.org/support/topic/legitimate-comments-marked-as-spam/

**Comment by Zodiac1978** [comment]
It looks like this is problem with the output buffering and maybe #357 is a related issue or a duplicate.

**Comment by florianbrinkmann** [comment]
Using the `comment_form_field_comment` filter as proposed by @pfefferle seems to be the best way to overcome that issue(s), I think. I created a PR for that: https://github.com/pluginkollektiv/antispam-bee/pull/392
