### ISSUE TITLE
Change wording for IP address lists

### ISSUE THREAD

**Issue by 2ndkauboy** [pluginkollektiv/antispam-bee#400]
The plugin is currently using the terms black/white (list) for it's lists of IP addresses to be blocked or allowed. I would ask to rename them:

 - `$black` => `$blocked` or `$denied`
 - `$white` => `$allowed`
 
 There are also two options `country_black` and `country_white` which we would have to migrate to new names.

**Comment by 2ndkauboy** [comment]
In the UI we even name those lists [denied](https://github.com/pluginkollektiv/antispam-bee/blob/0c9aefb3ae59ba9616778bcafc35c33e1f32cbd2/inc/gui.class.php#L304) and [allowed](https://github.com/pluginkollektiv/antispam-bee/blob/0c9aefb3ae59ba9616778bcafc35c33e1f32cbd2/inc/gui.class.php#L319).

**Comment by florianbrinkmann** [comment]
👍🏻
