### ISSUE TITLE
Test WordPress 5.8 compatibility

### ISSUE THREAD

**Issue by florianbrinkmann** [pluginkollektiv/antispam-bee#409]
WordPress 5.8 is almost there, so we should check ASB for compatibility.

I just tried ASB with the latest Release Candidate and was not able to find issues. Trac lists 4 tickets for the Comments component, and those look not like they touch anything ASB related: https://core.trac.wordpress.org/query?status=closed&component=Comments&milestone=5.8&group=component&col=id&col=summary&col=owner&col=type&col=priority&col=component&col=version&order=priority

**Comment by pfefferle** [comment]
same here, no issues so far.
