### ISSUE TITLE
Fix broken links in documentation

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#411]
There are some broken links on https://antispambee.pluginkollektiv.org/

~~https://tamcore.eu/spammer-mit-fail2ban-und-antispam-bee-loswerden~~ (Wayback Machine)
~~https://wp.cemoir.com/antispam-bee~~ (Broken trackback deleted)
https:1https://antispambee.pluginkollektiv.org/news/2015/removal-of-allow-comments-only-in-certain-language/%23comment-1 [sic!]
https:2https://antispambee.pluginkollektiv.org/news/2014/antispam-bee-2-6-4/%23comment-2 [sic!]
~~https://plus.google.com/wm/4/+SergejM%C3%BCller/posts/73EbP6F1BgC~~ (Wayback Machine)
~~https://github.com/sergejmueller/sergejmueller.github.io/wiki/Fail2Ban:-IP-Firewall~~ (Wayback Machine)
~~https://antispambee.pluginkollektiv.org/de/dokumentation/hooks~~ (Anchor instead of page)
https://web.archive.org/web/20190313131910/https://github.com/pluginkollektiv/antispam-bee/wiki/de-News-2012-11-24

Any help to fix this is much appreciated!

**Comment by pfefferle** [comment]
archive.org?

**Comment by Zodiac1978** [comment]
Looking in this moment. Google+ is not indexed there ... but maybe some of the others.

**Comment by Zodiac1978** [comment]
https://web.archive.org/web/20130822054221/http://tamcore.eu/spammer-mit-fail2ban-und-antispam-bee-loswerden/

**Comment by Zodiac1978** [comment]
https://web.archive.org/web/20201011111913/https://github.com/sergejmueller/sergejmueller.github.io/wiki/Fail2Ban:-IP-Firewall

**Comment by Zodiac1978** [comment]
https://web.archive.org/web/20190313131712/https://plus.google.com/+SergejM%C3%BCller/posts/73EbP6F1BgC

**Comment by Zodiac1978** [comment]
On https://antispambee.pluginkollektiv.org/de/news/2012/edition-2012/ is a link to wrong link. https://web.archive.org/web/20190313131910/https://github.com/pluginkollektiv/antispam-bee/wiki/de-News-2012-11-24 instead of the mentioned Google+ post.

**Comment by Zodiac1978** [comment]
These 404s are now fixed. But we have still some internal links that are linking to the Github wiki:

https://github.com/pluginkollektiv/antispam-bee/wiki/en-Hooks (on https://antispambee.pluginkollektiv.org/documentation/) - FIXED
https://github.com/pluginkollektiv/antispam-bee/wiki/en-Documentation (on https://antispambee.pluginkollektiv.org/documentation/)
https://github.com/pluginkollektiv/antispam-bee/wiki/de-Dokumentation (on https://antispambee.pluginkollektiv.org/de/dokumentation/)
