### ISSUE TITLE
Is it possible to get antispam-bee working with wpgraphql?

### ISSUE THREAD

**Issue by hdahlheim** [pluginkollektiv/antispam-bee#420]
Hey, I was wondering if it's possible to get Antispam-bee working with wpgraphql. 
We are currently using both plugins because we transitioned to a headless WordPress installation but creating comments over the GraphQL endpoint seems to bypass Antispam Bee.

[According to Jason Bahl](https://spectrum.chat/wpgraphql/general/does-the-createcomment-mutation-benefit-from-akismet-or-similar~091dc9b2-9399-4333-a3ba-226c655939d5?m=MTU1MDc2OTY1Nzg4MQ==), the maintainer of wpgraphql, plugins that hook into the WordPress methods to create comments should work out of the box, but I don't know if Antispam Bee works this way. 

I apologize if my question is out of scope or if this is the wrong place to ask these questions. 
I don't do WordPress development that often, so I'm kinda lost 😅

Thanks for the help <3

**Comment by Zodiac1978** [comment]
Hi @hdahlheim and thanks for the question!

You wrote:
> creating comments over the GraphQL endpoint seems to bypass Antispam Bee

We are using core filter to modify the comment form and some other methods to detect spam. But our Honeypot gets 99.9% of the spam. So I am wondering what is happening here. I have never used wpgraphql, so unfortunately I have no idea what is going wrong here.

You could enable the BBCode links check and try to comment with a BBCode link. If it get marked as spam, everything is working as expected. 

If *every* comment gets marked as spam with reason `honeypot` there is a problem with the comment form and applying our changes to it (no idea how this could work with a headless WP).

If you could share more details about your setup and/or markup used, then we try to get this working with you.

Maybe someone from the team has more experience with wpgraphql. Maybe @schlessera or @websupporter ?

**Comment by websupporter** [comment]
I am sorry, but Antispam Bee does currently not work in headless or semi-headless environments.

Antispam Bee injects the honeypot into the form and the `POST` Request sends this to _wp-comments-post.php_. There we check for this information and currently we are bound to _wp-comments-post.php_ here 
https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L1112-L1114

and here
https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L1157

**Comment by hdahlheim** [comment]
Hi @Zodiac1978, @websupporter thanks a lot for the help :)

Okay, in this case, we'll have to find another way to prevent spam comments.

**Comment by krafit** [comment]
@websupporter, what about all the additional filters beside the honeypot?

**Comment by websupporter** [comment]
[`_verify_comment_request()`](https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L1420) which verifies a request gets only executed on _wp-comments-post.php_:
https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L1157-L1159
