### ISSUE TITLE
Problem with translation

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#423]
**Describe the bug**
We are using translation function before we are loading the translation.

**To Reproduce**
First occurrence of i18n function is here:
https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L486

Localization is loaded later here:
https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L578-L582

**Expected behavior**
We should load the translation file before we use any i18n functions. Otherwise we produce problems (for example i18n files are loaded twice or user locale vs. site locale is not working)

**Additional context**
Query Monitor is showing `_load_textdomain_just_in_time()` instead of the correct `load_plugin_textdomain` call in the language tab.

**Comment by Zodiac1978** [comment]
This leads to two possible problems:
* The translation is loaded twice (performance/memory problem)
* The first translation could be too early for the user locale setting and therefore could load the website language instead of the user language (in case of incomplete translation this could lead to mixed language strings)

**Comment by florianbrinkmann** [comment]
We could remove the `add_action()` calls with the `load_plugin_lang()` function and move the call above the `_init_internal_vars()` call, like that:

```
if ( self::_current_page( 'dashboard' ) || self::_current_page( 'plugins' ) || self::_current_page( 'options' ) ) {
	self::load_plugin_lang();
}
```

**Comment by Zodiac1978** [comment]
Have you tried this @florianbrinkmann ?
Any chance to try this for the 2.10.1 release?

**Comment by florianbrinkmann** [comment]
Ah, sorry, missed that comment @Zodiac1978. If I remember correctly, I tested that, will verify that
