### ISSUE TITLE
HTML Validation Warning: The type attribute is unnecessary for JavaScript resources.

### ISSUE THREAD

**Issue by oldrup** [pluginkollektiv/antispam-bee#453]
The following code triggers a warning when HTML validating.

`<script data-noptimize type="text/javascript">document.getElementById("comment").setAttribute( "id", "a3b502efb795f86597eefdbc4db8cc85" );document.getElementById("d66a39b596").setAttribute( "id", "comment" );</script>`

![image](https://user-images.githubusercontent.com/17141205/163705017-20a80c89-41f3-4820-89c2-cdb5eedeeabc.png)

![image](https://user-images.githubusercontent.com/17141205/163704792-646c455f-9471-4a96-99b6-ed639d6000e9.png)

The `type="text/javascript"` can safely be removed for green lights across the board when validating. Most plugins and WP core removed it long time ago.

I've got a code snippet filtering the type from the HTML output, but I'd obviously would prefer warning free output out of the box.

Let me know if I can assist in any way.

Bjarne

**Comment by stklcode** [comment]
Is this different from #448 which is yet fixed in the master branch?

**Comment by oldrup** [comment]
Ooops. No, it's the same issue, sorry. Appears my GitHub issue search skills needs to be improved.

But maybe you can enlighten me on the workflow. Once fixed in the master branch, it takes some time before it's published on WordPress.org? 

Can I pitch in on the testing, by downloading and installing the master branch manually?

**Comment by oldrup** [comment]
Downloaded and installed the master branch and the type attribute is no longer present. Closing this issue. Thanks again :)

![image](https://user-images.githubusercontent.com/17141205/163709387-f99573df-7e8a-4aa7-9a45-c69d9e00571b.png)

**Comment by stklcode** [comment]
> But maybe you can enlighten me on the workflow. Once fixed in the master branch, it takes some time before it's published on WordPress.org?

The “master“ branch represents the latest development state. The plugin is pushed to w.org once a new version is tagged from that state. For point and major releases there are typically milestones to track the progress. Minor bugfix releases can basically happen whenever necessary based on team decisions (I am not deeply involved in ASB, someone correct me if this plugin differs from that workflow)
