### ISSUE TITLE
Change string with deprecated information

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#46]
After switch from Tornevall-DNSBL to Stop Forum Spam we should change this string:
https://github.com/pluginkollektiv/antispam-bee/blob/fc14de14a4a06dc1dabcb960e95c64ec1a4e4107/inc/gui.class.php#L230

See:
https://github.com/pluginkollektiv/antispam-bee/blob/fc14de14a4a06dc1dabcb960e95c64ec1a4e4107/README.md#L169
and
https://github.com/pluginkollektiv/antispam-bee/blob/fc14de14a4a06dc1dabcb960e95c64ec1a4e4107/antispam_bee.php#L1652

**Comment by timse201** [comment]
can be closed
