### ISSUE TITLE
Link to ISO codes not helpful

### ISSUE THREAD

**Issue by stkjj** [pluginkollektiv/antispam-bee#462]
The link for the explanation of ISO Codes despite refering to the ISO.org website is not really helpful as I brings you to a general overview where one has to identify the correct link for the list. It would be better to link directly to this list https://www.iso.org/obp/ui/#search or even make use of the wikipedia-entry https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

![Bildschirmfoto 2022-07-28 um 10 37 39](https://user-images.githubusercontent.com/832642/181461396-2ce9e138-7586-42d5-9a4a-67eca6b2082b.jpg)

**Comment by Zodiac1978** [comment]
Hi @stkjj,

sorry for not answering for so long here ...

I think the search is not the best UI/UX here, as it would mean the user needs to click the correct radio button and look for a country (or get the idea they can search for an empty search string).

Linking to the Wikipedia article looks better IMHO.

Maybe some more people can chime in here, so we get a consensus of which link we should add.

Thanks for your contribution!

All the best
Torsten

**Comment by stklcode** [comment]
I guess what @stkjj wanted to link is this page:
![isocodes](https://user-images.githubusercontent.com/12963621/198972769-05e42887-a5ff-4fe1-af6c-14de7eb7e467.png)

Unfortunately, the link (https://www.iso.org/obp/ui/#search) refers to the empty search page, if visited without a previous session.

This link would be better, if we wanted to link the iso.org source: https://www.iso.org/obp/ui/#search/code/

**Comment by florianbrinkmann** [comment]
+1 for linking the Wikipedia article
