### ISSUE TITLE
Add PHP 8.1 to tests in our Github Actions

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#480]
**Describe the bug**
We don't check for PHP 8.1 which is released one year ago: https://www.php.net/supported-versions.php

**To Reproduce**
1. See: https://github.com/pluginkollektiv/antispam-bee/blob/master/.github/workflows/tests.yml

**Expected behavior**
We should test PHP for 8.1 which is getting more usage.

**Comment by michaelH91** [comment]
Thank you Torsten!

**Comment by Zodiac1978** [comment]
Looks like we could use this list:
https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/

@florianbrinkmann do you have some time to update this file (or even better: explain to us how to keep up to date here)?

**Comment by stklcode** [comment]
PHP 8.0 with WP 5.6-6.0 and PHP 8.1 with WP _latest_ and _nightly_ have been added to the test matrix in #481. Let's consider this done.
