### ISSUE TITLE
Documentation - privacy hints

### ISSUE THREAD

**Issue by timse201** [pluginkollektiv/antispam-bee#49]
~~**no context:**~~
~~https://github.com/pluginkollektiv/antispam-bee/wiki/de-Funktionsweise~~

~~Mit der letztens vorgestellten und ausführlich beschriebenen Möglichkeit, wo es darum ging Templates händisch für den Spamabwehr vorzubereiten, reduzierte sich das gesamte Spam-Aufkommen bis auf mickrige, jedoch zugegeben nervige fünf Prozent. Kein schlechter Wert, doch es geht definitiv besser: Seit dem Einsatz von Antispam Bee ist überhaupt kein automatischer Spam mehr durchgekommen.~~

~~Im Klartext: Absolut kein Spam mehr im Blog!~~

~~**wrong info:**~~
~~https://github.com/pluginkollektiv/antispam-bee/wiki/de-Funktionen~~

~~… verwendet kein **JavaScript**, keine Cookies, keine Timeouts.~~

~~**FAQ outdated:**~~
~~Warum und wie kann ich Antispam Bee unterstützen?~~
~~Die wichtige Frage nach Warum?: Die permanente Weiterentwicklung des Plugins, die Bearbeitung der Nutzeranfragen auf unterschiedlichsten Kanälen, die Überwachung des Spam-Aufkommens, zahlreiche Testphasen und Updates beanspruchen Zeit. Viel Zeit. **Zur Analyse der Spam-Kommentare werden sogenannte „Fässer für Honig oder Honey Pots“ aufgestellt, um Spammer anzulocken und deren Verhalten auszuwerten. Dafür sind mehrere Server angemietet. Selbst im Antispam Bee Plugin wird auf kostenpflichtige Dienstleistungen zurückgegriffen (beispielsweise die Erkennung des Herkunftslandes), um auf zuverlässige, aktuelle und stets erreichbare Daten zurückgreifen zu können.** Kurz: Der Betrieb der WordPress-Erweiterung und die Forschung im Segment „Antispam“ kosten zusätzlich auch Geld.~~

~~think we could delete this and add a donate site~~

~~Wie finde ich den Ländercode eines Spam-Kommentars heraus?~~
~~but: #30~~

~~**Documentation outdated:**~~
~~https://github.com/pluginkollektiv/antispam-bee/wiki/de-Dokumentation#bestimmte-l%C3%A4nder-blockieren-bzw-erlauben~~
~~https://github.com/pluginkollektiv/antispam-bee/wiki/de-Dokumentation#kommentare-nur-in-einer-sprache-zulassen~~

**please check this [table](https://github.com/pluginkollektiv/antispam-bee/wiki/en-Documentation#suspicion-of-spam-detection)**
don't know if the identification is being translated and these are the exact words

**please add privacy hints**
[Trust commenters with a Gravatar](https://github.com/pluginkollektiv/antispam-bee/wiki/en-Documentation#trust-commenters-with-a-gravatar)
[Use a public antispam database](https://github.com/pluginkollektiv/antispam-bee/wiki/en-Documentation#use-a-public-antispam-database)
[Block comments from specific countries](https://github.com/pluginkollektiv/antispam-bee/wiki/en-Documentation#block-comments-from-specific-countries)
[Allow comments only in certain language](https://github.com/pluginkollektiv/antispam-bee/wiki/en-Documentation#allow-comments-only-in-certain-language)

**Comment by Zodiac1978** [comment]
no1: no context
This section could be deleted. I've done that already.

no2:  wrong info
Why wrong? We don't use Javascript (at the moment) for the **spam detection**.

no3: FAQ oudated
I will edit this section.

no4: documentation outdated
There is an information "Eingestellt: Antispam Bee 2.6.7" - maybe we should make this bold ;)
Some features are coming back in the next version, so I will change it accordingly.

**Comment by timse201** [comment]
thank you

**Comment by timse201** [comment]
https://github.com/pluginkollektiv/antispam-bee/wiki/de-Dokumentation#%C3%96ffentliche-spamdatenbank-ber%C3%BCcksichtigen
can i just edit the link to Tornevall? or is there something that needs to be added/changed?

what i dont want to do:
i dont want to translate the privacy hints because this should be provided by plugin author/maintainer and i think there are some legal terms to be added for eu and some other countries
I think no one wants to be held liable here ;)
thanks for your understanding

**Comment by timse201** [comment]
i'm finished with the translation
please check the head for things that needs to be done

**Comment by tyrann0us** [comment]
Hi all,
I just accidentally clicked "Revert Changes" here: https://github.com/pluginkollektiv/antispam-bee/wiki/de-H%C3%A4ufige-Fragen/_compare/3cbdab7%5E...3cbdab7 which reverted @timse201's last change (see https://github.com/pluginkollektiv/antispam-bee/wiki/de-H%C3%A4ufige-Fragen/_history).
Is there an quick way to undo this? I'm very sorry about this!

**Comment by timse201** [comment]
i think i restored it

**Comment by tyrann0us** [comment]
Maybe this: https://help.github.com/articles/changing-access-permissions-for-wikis/ would be helpful.

**Comment by websupporter** [comment]
privacy hint added for 
gravatar
stopforumspam
google translate

still needed for ip2nation

**Comment by timse201** [comment]
Thank you

**Comment by schlessera** [comment]
Modified english [table](https://github.com/pluginkollektiv/antispam-bee/wiki/en-Documentation#suspicion-of-spam-detection)

**Comment by timse201** [comment]
wikis are now restricted thanks @tyrann0us 
(needed access/rights to edit these parts)
