### ISSUE TITLE
Check for value of `website` field in the comment content

### ISSUE THREAD

**Issue by florianbrinkmann** [pluginkollektiv/antispam-bee#503]
I just noticed a spam comment where the website field was filled with a URL that was also linked to in the comment text. Is that something we could check for to detect spam, or is that something that also happens in valid comments?

**Comment by 2ndkauboy** [comment]
This can very well be a valid comment. I sometimes comment on other blogs, linking one of my personal blog posts and then also have my blog hompage in the `website` field.

**Comment by florianbrinkmann** [comment]
But checking if the URLs are identical (and not only for a substring Match) would not match in that case, wouldn’t it?

**Comment by Zodiac1978** [comment]
Some people do not have a website and use this field to add a URL they want to mention. So I wouldn't recommend doing this. I would be afraid of too many false positives.

**Comment by florianbrinkmann** [comment]
Closing because might cause false-positives
