### ISSUE TITLE
Spam reason in email is empty

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#518]
I tried a message with a BBCode link in it and it got caught correctly as spam.

The spam reason is shown in the list table, but NOT in the mail. 

First reported in the forums: 
https://wordpress.org/support/topic/new-install-spam-reason-not-being-displayed-in-email-notifications/

**Comment by florianbrinkmann** [comment]
@Zodiac1978 related to #508, should be fixed with https://github.com/pluginkollektiv/antispam-bee/pull/517
