### ISSUE TITLE
Readme.txt contains outdated information

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#520]
**Describe the bug**
We removed the fake IP check in 2.9.2
> Maintenance: Removed Fake IP check (unreliable and producing false positives)

So, I think we should remove the line "Validate the IP address of commenters." in the readme.txt.

https://github.com/pluginkollektiv/antispam-bee/blob/master/readme.txt#L24

**Comment by anubhav1206** [comment]
Can I work on this?

**Comment by Zodiac1978** [comment]
@anubhav1206 There is already a PR for this. But thank you for the offer!
