### ISSUE TITLE
Outdated link for plugin installation

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#525]
In readme.txt and README.md there is an outdated link to the codex:
https://codex.wordpress.org/Managing_Plugins#Installing_Plugins

https://github.com/pluginkollektiv/antispam-bee/blob/master/readme.txt#L50

and

https://github.com/pluginkollektiv/antispam-bee/blob/master/README.md?plain=1#L44

The page shows:
> This page was moved to https://wordpress.org/support/article/managing-plugins/ except above language locator. 

So we could change link accordingly (maybe with the specific [anchor](https://wordpress.org/documentation/article/manage-plugins/#automatic-plugin-installation-1))

**Comment by hind-sagar-biswas** [comment]
I sent a pull request #526

**Comment by hind-sagar-biswas** [comment]
@Zodiac1978 are ya gonna accept the pull request?

**Comment by Zodiac1978** [comment]
@hind-sagar-biswas Yes, just wanted to check if we better use the anchor, as mentioned in my comment. But you closed your PR.

**Comment by hind-sagar-biswas** [comment]
> @hind-sagar-biswas Yes, just wanted to check if we better use the anchor, as mentioned in my comment. But you closed your PR.

Okay, I'll send again @Zodiac1978

**Comment by hind-sagar-biswas** [comment]
I sent a new PR #528

**Comment by hind-sagar-biswas** [comment]
> @hind-sagar-biswas Yes, just wanted to check if we better use the anchor, as mentioned in my comment. But you closed your PR.

By anchor do you want to use: https://wordpress.org/documentation/article/manage-plugins/#automatic-plugin-installation-1 this link?

**Comment by Zodiac1978** [comment]
Yes, I think this is the most useful one. It directly shows what to do next without looking for the correct section.

**Comment by hind-sagar-biswas** [comment]
@Zodiac1978 done

**Comment by Zodiac1978** [comment]
Fixed with #528
