### ISSUE TITLE
Spam comments not detected

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#54]
There are some reports of a massive spam wave which gets through:
https://wordpress.org/support/topic/the-plugin-passes-spam

We should analyze the comments and add custom patterns asap.

I will get a dump of 1000+ spam comments for analyzing I can share with the team.

**Comment by schlessera** [comment]
We've (re)added several features:

- Different mechanism for preparing the honeypot comment field.
- Additional regex filters.
- Country check.
- Language check.

**Comment by kevinpapst** [comment]
Hey, glad that you worked on this issue. I guess a lot of people worldwide are currently waiting for a fix for this issue...
Can you give me a hint how to get these fixes up and running? 
Unfortunately there is not a commit linked to this issue, only an upcoming release.  When will this release happen? 
Or how can we get the code directly? Simply clone master?

**Comment by schlessera** [comment]
@kevinpapst : Yes, these are all included in the current `master` branch. We are actively testing this branch at the moment, but if you are of the adventurous kind, you can either clone `master` or [download it as a ZIP file](https://github.com/pluginkollektiv/antispam-bee/archive/master.zip) to help as test. We would love to get some feedback.
I would expect the release to be done some time next week, as there are still some details we need to figure out before doing the actual release.
