### ISSUE TITLE
JS Nonce

### ISSUE THREAD

**Issue by websupporter** [pluginkollektiv/antispam-bee#57]
We could introduce an optionally JS feature.

We create a hidden field, which will get populated with a WP Nonce by Javascript. If the input fields value does not match: SPAM.

**Comment by swissspidy** [comment]
How safe is this? When you have a public route to get a nonce, what stops an attacker from fetching a nonce and populating a field with that nonce?

**Comment by websupporter** [comment]
Hi @swissspidy,
basically nothing, but they have to do it. So its another step, which needs to be taken. In the current PR, you need to know the public route and a nonce (`wp_rest`), so you would have to do some action, to get the correct nonce. But: This introduces a problem with cached pages right now and I think this PR needs some more thought.

Right now, it is not very high on my agenda. But I didn't want to close it, since this might be a feature, worth considering.

**Comment by websupporter** [comment]
wont fix for now.
