### ISSUE TITLE
Reduce tags to 5 and limit short description to 150 characters

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#580]
Readme: One or more tags were ignored. Please limit your plugin to 5 tags.
    Readme: The Short Description section is too long and was truncated. A maximum of 150 characters is supported.

<img width="956" alt="Bildschirmfoto 2024-03-24 um 13 08 40" src="https://github.com/pluginkollektiv/antispam-bee/assets/870475/5f962a4a-d1c4-49fc-847d-dff60a31a77d">

**Comment by Zodiac1978** [comment]
Status Quo:
<img width="303" alt="Bildschirmfoto 2024-03-24 um 17 13 12" src="https://github.com/pluginkollektiv/antispam-bee/assets/870475/f4437600-d649-45bf-935e-020d6a5fe181">

**Comment by Zodiac1978** [comment]
I would suggest removing `comment`, `pingback`, `trackback` as a first step

What do you think?

**Comment by Zodiac1978** [comment]
> Antispam plugin with a sophisticated tool set for effective day to day comment and trackback spam-fighting. Build with data protection and privacy in mind.

155 characters.

Asked ChatGPT for some ideas:
    "Antispam plugin equipped for daily comment and trackback spam control, prioritizing data protection and privacy."
    "Advanced antispam plugin combats comment and trackback spam, prioritizing data privacy."
    "Plugin fights comment and trackback spam daily, emphasizing data privacy."
    "Combat spam with our plugin's robust tools while safeguarding data privacy."
    "Efficiently fight comment and trackback spam, emphasizing data privacy."
    "Plugin designed for daily spam control while ensuring data privacy."
    "Safeguard data privacy while effectively combating comment and trackback spam."
    "Plugin offers powerful spam-fighting tools with a focus on data privacy."
    "Combat spam daily with our plugin, built with data protection in mind."
    "Plugin equipped for daily spam prevention, with a focus on data privacy."
    "Efficient spam-fighting plugin prioritizes data privacy and protection."

**Comment by 2ndkauboy** [comment]
Looking at the tags other antispam plugin use, I think we can remove the three tags you've mentioned.
