### ISSUE TITLE
Process pre-existing pending comments

### ISSUE THREAD

**Issue by szepeviktor** [pluginkollektiv/antispam-bee#614]
**Describe the question**

Is it possible to write a for loop to process existing "pending" comments?

Please help me with two sentences.
Thank you.

**Comment by Zodiac1978** [comment]
Sorry for the late response @szepeviktor 

There is no way to do this at the moment.

We have a branch/PR trying to achieve this, if you want to have a look:
https://github.com/pluginkollektiv/antispam-bee/pull/374

All the best
Torsten

**Comment by szepeviktor** [comment]
Thank you!!

**Comment by Zodiac1978** [comment]
This is handled in #281
