### ISSUE TITLE
Report Hangul writing signs (Korea) as spam

### ISSUE THREAD

**Issue by szepeviktor** [pluginkollektiv/antispam-bee#636]
**Describe the bug**
Am I going it right?
https://antispambee.pluginkollektiv.org/documentation/#antispam_bee_patterns

**To Reproduce**
```php
add_filter('antispam_bee_patterns', function ($patterns) {
    $patterns[] = ['body' => '\p{Hangul}']; // Unicode character property
    return $patterns;
});
```

Thank you!

**Comment by Zodiac1978** [comment]
This looks correct. It is the same pattern I included here:
https://github.com/Zodiac1978/custom-patterns-asb/blob/master/custom-patterns-asb.php#L90-L94

Is your question if this is the correct way or does it not work @szepeviktor ?

**Comment by szepeviktor** [comment]
> if this is the correct way

Yes.

Thank you for the link!
