### ISSUE TITLE
New feature: Mark as spam if comment contains xx links

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#69]
Like in the discussion settings:
https://github.com/WordPress/WordPress/blob/4cf5550d8d7f227d760f779f250a8fb2cfa2c8c9/wp-admin/options-discussion.php#L153

we could add an option for the allowed maximum of links:
https://github.com/WordPress/WordPress/blob/324e79a50608cc8b327b83e0a357777f6ffcf938/wp-includes/comment.php#L51

If this amount x (has to be greater than the WP option) is reached, the comment is considered as spam.

So 0-1 links are okay, 2 (WP default) or more are held for moderation. If x links are reached the comment is spam.

Opinions?

**Comment by timse201** [comment]
maybe a soft and a hardblock?
softblock for moderation when a limit is reached
hardblock will delete it immediately when a limit is reached

so the user can control it his way and if we make 2 checkboxes he can say i only want to hardblock or softblock them

**Comment by websupporter** [comment]
My opinion: If we are to strict on the filters, we will run into a lot of false positives. I think this is why the plugin tries to avoid using filters extensively and relying on other methods. I think in the long run we probably will have to introduce more and better filters, but since right now, the filters are spam/no-spam and do not come with a weighing, I would be very careful in introducing new ones (we discussed some of the problems in the regex-PR, https://github.com/pluginkollektiv/antispam-bee/pull/48).

What if you are commenting using URLs to pictures you have shot? Something like

> Hey Jane,
> Great pictures from X. During my holidays, I was there too. Have a look, what nice pictures I took
> https://example.com/picture-1.jpg
> Here we have been in X while sunset
>
> https://example.com/picture-2.jpg
> Even better while sunrise, isn't it. Oh man what a night!
>
> https://example.com/picture-3.jpg
> So we needed some rest the next day. Here on the beach :P 
>
> Hope to see you soon.

**Comment by timse201** [comment]
True
That was my thought behind the hard and softblock

**Comment by websupporter** [comment]
what would softblock mean, when i have the setting: do not delete the spam immediatly?

**Comment by timse201** [comment]
please see post 2

**Comment by swissspidy** [comment]
Is this a frequent problem?

If we'd do this, I'd keep it simple. No 2 checkboxes, no "soft" or "hard" blocks. For soft blocks you have the discussion setting powered by WordPress that puts the comment into moderation if it contains too many links.

> If this amount x (has to be greater than the WP option) is reached, the comment is considered as spam.

Making sure the amount is greater than the WP option is tricky from a UX point of view. You'd need to point the user to the discussion settings if they need to lower the value there. Then come back and adjust the ASB setting… Not ideal. We could theoretically copy the WP option in the ASB settings, but that seems unexpected to me as well.

I can't find to seem a good solution for this.

**Comment by Zodiac1978** [comment]
> Making sure the amount is greater than the WP option is tricky from a UX point of view.

That's true.

I've analyzed hundreds of spam from our google form feedback and this was one way to detect spam, but the problem with the UI and especially this disadvantage:

> What if you are commenting using URLs to pictures you have shot?

are leading me to the decision to close my own feature request.

If anyone wants to fights spam this way I have a regex in my plugin to do the same thing:
https://github.com/Zodiac1978/custom-patterns-asb/blob/master/custom-patterns-asb/custom-patterns-asb.php#L58
