### ISSUE TITLE
Add unparsed raw URL to pattern array

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antispam-bee#71]
The $host variable is containing a filtered version of the $url
https://github.com/pluginkollektiv/antispam-bee/blob/master/antispam_bee.php#L1405

Maybe we should add the unfiltered $url to the pattern array function too.

**Comment by schlessera** [comment]
@Zodiac1978 I added this under the `'rawurl'` key, so you can experiment with your custom patterns.
