### ISSUE TITLE
Thank you alert at donation

### ISSUE THREAD

**Issue by timse201** [pluginkollektiv/antispam-bee#74]
i think it would be nice to add an alert - with a thank you - when you click on the paypal links
could be easily done with onClick="alert( 'Thank you!' )"

**Comment by websupporter** [comment]
A friendly Thank you is always a nice thing. But introduced in an `alert()` its quite a bad UX, since you want to donate, Paypal or whatever pops up in a new tab and you jump back to the old tab thanks to the `alert()`

**Comment by schlessera** [comment]
Could be a lightweight modal dialog instead. That would appear in the background and just be visible when the user comes back to the wp-admin window.

**Comment by timse201** [comment]
In Firefox the alert pops up and after pushing OK the link opens

**Comment by krafit** [comment]
For now, we do have more important features to deal with. I will close this issue for now.
