### ISSUE TITLE
Basic language check

### ISSUE THREAD

**Issue by schlessera** [pluginkollektiv/antispam-bee#75]
While we are trying to figure out how to bring back the full language detection, we could implement a more basic variant for a select set of languages that can be detected by the presence of their Unicode characters.

So, as an example, instead of detecting whether a given text is valid Chinese language, we just detect whether it contains Chinese characters.

This is not fool-proof, but probably a major improvement over no language filtering at all.

**Comment by Zodiac1978** [comment]
See: https://github.com/Zodiac1978/custom-patterns-asb/blob/master/custom-patterns-asb/custom-patterns-asb.php#L65

What about international context? Should be a nom-default option.

**Comment by schlessera** [comment]
Yes, something along those lines, but with the added ability for the user to select individual languages. By default, all languages would be accepted.

**Comment by websupporter** [comment]
Why not following the path layed out here https://github.com/pluginkollektiv/antispam-bee/issues/31 and reintroducing the Google API?

**Comment by schlessera** [comment]
As I understood that ticket, Google API would be nice, but we don't have a structure that could support the cost associated with using it. This will probably amount to something like a three-digit monthly expense, so it cannot easily be included without sponsoring or a way to produce income.

What I propose above would provide half of that benefit (for some of the most important languages related to spam) without any associated cost at all, and it would not prevent us from further researching into how to make Google API work or find a free/cheaper alternative.

**Comment by websupporter** [comment]
I see.

**Comment by schlessera** [comment]
Well, there's no problem in providing both, I guess. If we provide clear explanations, this will make sense to the user, and they can choose whether they want to provide for finer granularity, or are happy with the "good enough" free approach.

**Comment by krafit** [comment]
I think, the idea of reintroducing a language check - no matter if basic or via googles language API is key. 
But while a basic language detection is nice, the chance of false positives or negatives provide for less than optimal UX. 
So I'd opt for the full Google API implementation. As cited in #31 Sergej estimated a monthly cost of about 100€. Even if we double that, it's still an amount we could handle. Yes I know funding is an issue, but I'm pretty confident, we'll be able to cover that.

**Comment by schlessera** [comment]
Regarding false positives:
If a comment is made up of 90%+ Chinese symbols, it should be safe to assume that it is either a Chinese comment, or gibberish.

**Comment by websupporter** [comment]
I will close this for now, since we have the Google API right now. We can reopen any time we want to come back to this path I think.
