### ISSUE TITLE
Make country black/whitelist splitting more robust

### ISSUE THREAD

**Issue by schlessera** [pluginkollektiv/antispam-bee#80]
Currently, the country whitelist and blacklist options from the country check need the list to be separated by spaces. An option like `RU,CH` or `CH;RU` will fail to work.

The code to split the string into separate codes should be made more robust to allow for the most common ways of putting a collection into a string.

**Comment by timse201** [comment]
If we want to do that we should include it now or we will get responds that it won't work anymore or why this change etc.

**Comment by schlessera** [comment]
Yes, I agree. It should be a small change, I'll see whether I can get to it.

PS: Haha, I marked Switzerland as an offending country above instead of China. :) That should have been `CN` in the examples.
