### ISSUE TITLE
Broken localization in `Antispam_Bee_GUI::_build_select()`

### ISSUE THREAD

**Issue by schlessera** [pluginkollektiv/antispam-bee#81]
The method `Antispam_Bee_GUI::_build_select()` contains a broken localization, where the the text to be translated is not a literal string, but a variable `$v`. This will not work with `gettext`, which only does very basic string substitution.

**Comment by websupporter** [comment]
Reference https://github.com/pluginkollektiv/antispam-bee/blob/master/inc/gui.class.php#L151

**Comment by schlessera** [comment]
Resolved through #112 .
