### ISSUE TITLE
Broken localization in `Antispam_Bee_Columns::print_plugin_column()`

### ISSUE THREAD

**Issue by schlessera** [pluginkollektiv/antispam-bee#82]
The method `Antispam_Bee_Columns::print_plugin_column()` contains a broken localization, where the the text to be translated is not a literal string, but a variable `$spam_reasons[ $spam_reason ]`. This will not work with `gettext`, which only does very basic string substitution.

**Comment by websupporter** [comment]
Reference https://github.com/pluginkollektiv/antispam-bee/blob/master/inc/columns.class.php#L63

**Comment by schlessera** [comment]
Resolved with #111
