### ISSUE TITLE
Local IP Blacklist

### ISSUE THREAD

**Issue by apermo** [pluginkollektiv/antispam-bee#84]
I received at least 10-20 spam comments today on one of my lesser sites.
All from the same IP Adress (in russia).

I like the option of getting an email on spam comments, but in this case it was pretty annoying, but this lead to the idea.

If an IP sents multiple spam comments why not block it completely.

In my idea, I would add a new function to anti spam bee like:

function is_spammy_ip( $ip )

it returns true if the IP has been sending at least n spam comments within the last x hours (configurable from backend).

First of all this function could be added at the very beginning of the spam detection funnel.
And second, a developer could call the function himself from within the theme, and either completely block access, or block the comment form, or redirect him to a honeypot or whatever.

**Comment by timse201** [comment]
This could flag normal user who are legit, too.
So the number must be high and the profit minimal; I think

**Comment by schlessera** [comment]
I think the actual problem is that emails sent when spam was detected should be throttled. We should look into adding an option to send daily or weekly digests.

In https://github.com/pluginkollektiv/antispam-bee/issues/26 , another plugin was suggested to solve this, but given that spam can often come in waves, having this included in ASB couldn't hurt.

**Comment by Zodiac1978** [comment]
Problems with this idea:
1. PC is infected and sends spam (aka botnet). IP is legit. Blocking will be harming regular commenters.
2. Botnet is used and the IP is changing for each comment.
3. Spammer is using a proxy/different proxys. Blocking will be problematic. 
4. Blocking a comment which is exactly the same is great (Local DB spam), but the challenge is the first one. How do we detect the first spam comment without manual work?

**Comment by schlessera** [comment]
Closing this, as the actual problem is the large number of emails being received. The individual comments are already correctly being recognized as spam.
