### ISSUE TITLE
Save settings button is off

### ISSUE THREAD

**Issue by schlessera** [pluginkollektiv/antispam-bee#92]
On my Retina screen at full width, the "Save Settings" button slips into a fourth column:

<img width="1489" alt="screenshot 2017-02-03 11 20 10" src="https://cloud.githubusercontent.com/assets/83631/22587668/e3191618-ea02-11e6-9202-d7845a778a22.png">

**Comment by krafit** [comment]
On a 15" Retina (Macbook Pro Late 2016) the whole service-column is separate 🤔 

![pasted image at 2017_02_03 11_28](https://cloud.githubusercontent.com/assets/1038789/22588041/6eb777f4-ea04-11e6-9e1a-b1105734971e.png)

**Comment by timse201** [comment]
@krafit That is supposed to be like that. if you have 5 colums the save settings button is separate, too

@schlessera thats because we use margin right for the service links will make a pr

**Comment by schlessera** [comment]
Fixed by #94
